import "lib/gui.ny"

var passed = 0
var failed = 0

def assert_eq(label, got, expected):
    if str(got) == str(expected):
        passed = passed + 1
    else:
        failed = failed + 1
        print "  FAIL [" + label + "] got=" + str(got) + " expected=" + str(expected)

def assert_true(label, val):
    if val:
        passed = passed + 1
    else:
        failed = failed + 1
        print "  FAIL [" + label + "] expected true, got " + str(val)

def section(name):
    print "  " + name + " ..."

print "=== GUI TEST SUITE ==="

# ─── Color ────────────────────────────────────────────────────────────────────
section("Color")
var c = Color(255, 128, 0, 255)
assert_eq("r", c.r, 255)
assert_eq("g", c.g, 128)
assert_eq("b", c.b, 0)
assert_eq("a", c.a, 255)
var hex = c.to_hex()
assert_true("hex starts #", string_startswith(hex, "#"))
var c2 = c.darken(0.5)
assert_true("darken r", c2.r < c.r)
var dark_c = Color(100, 50, 0, 255)
var c3 = dark_c.lighten(0.5)
assert_true("lighten r", c3.r > dark_c.r)
var c4 = c.with_alpha(100)
assert_eq("with_alpha", c4.a, 100)
var c5 = Color(0, 0, 255, 255)
var lerped = c.lerp(c5, 0.5)
assert_true("lerp b", lerped.b > 0)

# ─── Palette ─────────────────────────────────────────────────────────────────
section("Palette")
var pal = Palette()
assert_true("accent exists", pal.ACCENT != none)
assert_true("success exists", pal.SUCCESS != none)
assert_true("danger exists", pal.DANGER != none)

# ─── Rect ─────────────────────────────────────────────────────────────────────
section("Rect")
var r = Rect(10, 20, 100, 50)
assert_eq("x", r.x, 10)
assert_eq("y", r.y, 20)
assert_eq("w", r.w, 100)
assert_eq("h", r.h, 50)
assert_eq("right", r.right(), 110)
assert_eq("bottom", r.bottom(), 70)
assert_eq("center_x", r.center_x(), 60)
assert_eq("center_y", r.center_y(), 45)
assert_true("contains inner", r.contains(50, 40))
assert_true("not contains outer", not r.contains(5, 5))
var r2 = Rect(50, 40, 80, 60)
assert_true("intersects", r.intersects(r2))
var r3 = Rect(200, 200, 50, 50)
assert_true("no intersect", not r.intersects(r3))
var re = r.expand(5)
assert_eq("expand x", re.x, 5)
assert_eq("expand w", re.w, 110)
var rs = r.shrink(5)
assert_eq("shrink x", rs.x, 15)
assert_eq("shrink w", rs.w, 90)
var rm = r.moved(5, 10)
assert_eq("moved x", rm.x, 15)
assert_eq("moved y", rm.y, 30)

# ─── Font ─────────────────────────────────────────────────────────────────────
section("Font")
var f = Font("sans-serif", 14, false, false)
assert_eq("family", f.family, "sans-serif")
assert_eq("size", f.size, 14)
assert_eq("bold", f.bold, false)
assert_eq("italic", f.italic, false)
var fb = Font("serif", 18, true, true)
assert_eq("bold2", fb.bold, true)
assert_eq("italic2", fb.italic, true)

# ─── Theme ────────────────────────────────────────────────────────────────────
section("Theme")
var th = Theme()
assert_true("bg exists", th.bg != none)
assert_true("accent exists", th.accent != none)
var dark = Theme()
var light = dark.light()
var dark_r = dark.bg.r
var light_r = light.bg.r
assert_true("themes differ", dark_r != light_r)

# ─── Event ────────────────────────────────────────────────────────────────────
section("Event")
var ev = Event("mousedown")
assert_eq("type", ev.type, "mousedown")
assert_eq("x init", ev.x, 0)
assert_eq("consumed init", ev.consumed, false)
ev.consume()
assert_eq("consumed", ev.consumed, true)
assert_true("is_mouse", ev.is_mouse())
assert_true("not keyboard", not ev.is_keyboard())
var click_ev = Event("click")
assert_true("is_click", click_ev.is_click())
var kev = Event("keydown")
assert_true("is_keyboard", kev.is_keyboard())
kev.key = "enter"
assert_true("is_key", kev.is_key("enter"))

# ─── Widget ───────────────────────────────────────────────────────────────────
section("Widget")
var w = Widget(0, 0, 200, 100)
assert_eq("rect x", w.rect.x, 0)
assert_eq("visible init", w.visible, true)
assert_eq("enabled init", w.enabled, true)
w.set_pos(10, 20)
assert_eq("set_pos x", w.rect.x, 10)
w.set_size(300, 150)
assert_eq("set_size w", w.rect.w, 300)
w.hide()
assert_eq("hidden", w.visible, false)
w.show()
assert_eq("shown", w.visible, true)
w.disable()
assert_eq("disabled", w.enabled, false)
w.enable()
assert_eq("enabled", w.enabled, true)

# ─── Button ───────────────────────────────────────────────────────────────────
section("Button")
var btn = Button(10, 10, 120, 36, "Click Me")
assert_eq("label", btn.label, "Click Me")
assert_eq("variant", btn.variant, "primary")
btn.set_variant("secondary")
assert_eq("variant set", btn.variant, "secondary")
assert_true("btn has label", btn.label == "Click Me")
var clicked = false
def on_click(e):
    clicked = true
btn.on("click", on_click)
var ce = Event("click")
btn.emit(ce)
assert_true("clicked", clicked)
btn.set_pos(50, 50)
assert_eq("btn pos x", btn.rect.x, 50)
btn.hide()
assert_eq("btn hidden", btn.visible, false)
btn.show()
assert_eq("btn shown", btn.visible, true)
btn.disable()
assert_eq("btn disabled", btn.enabled, false)
btn.enable()
assert_eq("btn enabled", btn.enabled, true)

# ─── Label ────────────────────────────────────────────────────────────────────
section("Label")
var lbl = Label(10, 10, 200, 30, "Hello World")
assert_eq("text", lbl.text, "Hello World")
lbl.set_text("Updated")
assert_eq("set_text", lbl.text, "Updated")
lbl.set_color(Color(255, 0, 0, 255))
assert_eq("color r", lbl.color.r, 255)
lbl.set_pos(20, 20)
assert_eq("pos y", lbl.rect.y, 20)

# ─── TextInput ────────────────────────────────────────────────────────────────
section("TextInput")
var ti = TextInput(10, 10, 200, 36, "Enter text...")
assert_eq("placeholder", ti.placeholder, "Enter text...")
assert_eq("value init", ti.value, "")
ti.clear()
assert_eq("cleared", ti.value, "")
ti.hide()
assert_eq("hidden", ti.visible, false)

# ─── Checkbox ─────────────────────────────────────────────────────────────────
section("Checkbox")
var cb = Checkbox(10, 10, "Remember me")
assert_eq("label", cb.label, "Remember me")
assert_eq("checked init", cb.checked, false)
var toggled = false
def on_toggle(e):
    toggled = true
cb.on("change", on_toggle)
var te = Event("change")
cb.emit(te)
assert_true("toggled", toggled)

# ─── Slider ───────────────────────────────────────────────────────────────────
section("Slider")
var sl = Slider(10, 10, 200, 0.0, 100.0, 50.0)
assert_eq("min", sl.min_val, 0.0)
assert_eq("max", sl.max_val, 100.0)
assert_eq("value", sl.value, 50.0)
sl.hide()
assert_eq("hidden", sl.visible, false)
sl.show()

# ─── ProgressBar ──────────────────────────────────────────────────────────────
section("ProgressBar")
var pb = ProgressBar(10, 10, 200, 20)
assert_eq("value init", pb.value, 0.0)
pb.set_value(75.0)
assert_eq("value set", pb.value, 75.0)
assert_eq("percent", pb.percent(), 75.0)
pb.set_value(0.0)
assert_eq("reset", pb.percent(), 0.0)
pb.set_value(120.0)
assert_eq("clamped max", pb.value, 100.0)

# ─── Panel ────────────────────────────────────────────────────────────────────
section("Panel")
var pnl = Panel(0, 0, 400, 300)
var b1 = Button(10, 10, 80, 30, "A")
var b2 = Button(10, 50, 80, 30, "B")
pnl.add(b1)
pnl.add(b2)
assert_eq("child count", pnl.child_count, 2)
pnl.hide()
assert_eq("hidden", pnl.visible, false)

# ─── VBox ─────────────────────────────────────────────────────────────────────
section("VBox")
var vb = VBox(0, 0, 200, 8)
var l1 = Label(0, 0, 200, 24, "A")
var l2 = Label(0, 0, 200, 24, "B")
var l3 = Label(0, 0, 200, 24, "C")
vb.add(l1)
vb.add(l2)
vb.add(l3)
assert_eq("count", vb.count, 3)
assert_eq("total_height", vb.total_height(), 96)

# ─── HBox ─────────────────────────────────────────────────────────────────────
section("HBox")
var hb = HBox(0, 0, 36, 8)
var b3 = Button(0, 0, 80, 36, "X")
var b4 = Button(0, 0, 80, 36, "Y")
hb.add(b3)
hb.add(b4)
assert_eq("count", hb.count, 2)
assert_eq("total_width", hb.total_width(), 176)

# ─── GridLayout ───────────────────────────────────────────────────────────────
section("GridLayout")
var gl = GridLayout(0, 0, 3, 120, 80, 8)
gl.add(Label(0, 0, 120, 80, "A"))
gl.add(Label(0, 0, 120, 80, "B"))
gl.add(Label(0, 0, 120, 80, "C"))
gl.add(Label(0, 0, 120, 80, "D"))
assert_eq("count", gl.count, 4)
assert_eq("total_width", gl.total_width(), 376)
assert_eq("total_height", gl.total_height(), 168)
gl.clear()
assert_eq("cleared", gl.count, 0)

# ─── Modal ────────────────────────────────────────────────────────────────────
section("Modal")
var mod = Modal(400, 300, "Confirm Delete")
assert_eq("title", mod.title, "Confirm Delete")
assert_eq("visible init", mod.visible, false)
mod.show(800, 600)
assert_eq("shown", mod.visible, true)
assert_eq("centered x", mod.rect.x, 200)
assert_eq("centered y", mod.rect.y, 150)
mod.hide()
assert_eq("hidden", mod.visible, false)

# ─── Toast / ToastManager ─────────────────────────────────────────────────────
section("Toast")
var t = Toast("Saved!", "success", 3000)
assert_eq("message", t.message, "Saved!")
assert_eq("type", t.type, "success")
assert_true("not expired", not t.is_expired())

section("ToastManager")
var tm = ToastManager(800)
tm.success("Saved!")
tm.error("Failed!")
tm.warning("Watch out!")
tm.info("FYI")
assert_eq("count", tm.count, 4)

# ─── Dropdown ─────────────────────────────────────────────────────────────────
section("Dropdown")
var dd = Dropdown(10, 10, 200, 36)
dd.add_item("Option A", "a")
dd.add_item("Option B", "b")
dd.add_item("Option C", "c")
assert_eq("item count", dd.item_count, 3)
dd.select(1)
assert_eq("selected", dd.selected, 1)
assert_eq("get_label", dd.get_label(), "Option B")
assert_eq("get_value", dd.get_value(), "b")
dd.select_by_value("c")
assert_eq("select_by_value", dd.selected, 2)
dd.set_placeholder("Choose...")
assert_eq("placeholder", dd.placeholder, "Choose...")
dd.clear_items()
assert_eq("cleared", dd.item_count, 0)
dd.hide()
assert_eq("hidden", dd.visible, false)
dd.show()
dd.disable()
assert_eq("disabled", dd.enabled, false)
dd.enable()

# ─── Switch ───────────────────────────────────────────────────────────────────
section("Switch")
var sw = Switch(10, 10, "Dark mode")
assert_eq("label", sw.label, "Dark mode")
assert_eq("checked init", sw.checked, false)
sw.toggle()
assert_eq("toggled", sw.checked, true)
sw.toggle()
assert_eq("toggled back", sw.checked, false)
sw.set_checked(true)
assert_eq("set_checked", sw.checked, true)
var sw_changed = false
def on_sw_change(e):
    sw_changed = true
sw.on("change", on_sw_change)
var sce = Event("change")
sw.emit(sce)
assert_true("sw changed", sw_changed)

# ─── RadioButton / RadioGroup ─────────────────────────────────────────────────
section("RadioButton")
var rb1 = RadioButton(10, 10, "Small", "size", "sm")
var rb2 = RadioButton(10, 40, "Medium", "size", "md")
var rb3 = RadioButton(10, 70, "Large", "size", "lg")
assert_eq("rb1 label", rb1.label, "Small")
assert_eq("rb1 value", rb1.value, "sm")
assert_eq("rb1 not selected", rb1.selected, false)
rb1.set_selected(true)
assert_eq("rb1 selected", rb1.selected, true)

section("RadioGroup")
var rg = RadioGroup("size")
rg.add(rb1)
rg.add(rb2)
rg.add(rb3)
assert_eq("count", rg.count, 3)
rg.select("md")
assert_eq("value", rg.get_value(), "md")
assert_eq("rb2 selected", rb2.selected, true)
assert_eq("rb1 deselected", rb1.selected, false)
var rg_changed = false
def on_rg_change(v):
    rg_changed = true
rg.on_change(on_rg_change)
rg.select("lg")
assert_eq("rg value lg", rg.get_value(), "lg")
assert_eq("rb3 selected", rb3.selected, true)

# ─── NumberInput ──────────────────────────────────────────────────────────────
section("NumberInput")
var ni = NumberInput(10, 10, 120, 36, 0.0, 100.0, 1.0)
assert_eq("value init", ni.value, 0.0)
ni.set_value(50.0)
assert_eq("set_value", ni.value, 50.0)
ni.increment()
assert_eq("incremented", ni.value, 51.0)
ni.decrement()
assert_eq("decremented", ni.value, 50.0)
ni.set_value(105.0)
assert_eq("clamped max", ni.value, 100.0)
ni.set_value(-5.0)
assert_eq("clamped min", ni.value, 0.0)
ni.disable()
assert_eq("disabled", ni.enabled, false)
ni.enable()

# ─── TextArea ─────────────────────────────────────────────────────────────────
section("TextArea")
var ta = TextArea(10, 10, 300, 120, "Write here...")
assert_eq("placeholder", ta.placeholder, "Write here...")
assert_eq("value init", ta.value, "")
ta.set_value("Hello\nWorld\nFoo")
assert_eq("line count", ta.line_count(), 3)
ta.set_value("Hello\nWorld\nFoo\nBar")
assert_eq("appended", ta.line_count(), 4)
ta.clear()
assert_eq("cleared", ta.value, "")
assert_eq("cleared lines", ta.line_count(), 1)
ta.disable()
assert_eq("readonly via disable", ta.enabled, false)
ta.enable()

# ─── Badge ────────────────────────────────────────────────────────────────────
section("Badge")
var bdg = Badge("New", "success")
assert_eq("text", bdg.text, "New")
assert_eq("variant", bdg.variant, "success")
bdg.set_text("Updated")
assert_eq("set_text", bdg.text, "Updated")
bdg.set_pos(100, 50)
assert_eq("pos x", bdg.x, 100)
bdg.hide()
assert_eq("hidden", bdg.visible, false)

# ─── Divider ──────────────────────────────────────────────────────────────────
section("Divider")
var dv = Divider(0, 100, 400, false)
assert_eq("length", dv.length, 400)
assert_eq("vertical", dv.vertical, false)
dv.set_label("Section")
assert_eq("label", dv.label, "Section")
dv.set_thickness(2)
assert_eq("thickness", dv.thickness, 2)
var dvv = Divider(200, 0, 300, true)
assert_eq("vertical2", dvv.vertical, true)

# ─── Card ─────────────────────────────────────────────────────────────────────
section("Card")
var card = Card(10, 10, 300, 200)
card.set_title("My Card")
card.set_subtitle("A subtitle")
assert_eq("title", card.title, "My Card")
assert_eq("subtitle", card.subtitle, "A subtitle")
var cb_btn = Button(10, 10, 80, 30, "Action")
card.add(cb_btn)
assert_eq("child count", card.child_count, 1)
card.set_pos(20, 30)
assert_eq("pos x", card.rect.x, 20)
card.hide()
assert_eq("hidden", card.visible, false)

# ─── Tooltip ──────────────────────────────────────────────────────────────────
section("Tooltip")
var tt = Tooltip("Click to save your work")
assert_eq("text", tt.text, "Click to save your work")
tt.set_text("Updated tip")
assert_eq("set_text", tt.text, "Updated tip")
var tr = Rect(100, 100, 80, 30)
tt.attach(tr)
tt.show_at(150, 90)
assert_eq("x", tt.x, 150)
assert_eq("visible", tt.visible, true)
tt.hide()
assert_eq("hidden", tt.visible, false)

# ─── Tabs ─────────────────────────────────────────────────────────────────────
section("Tabs")
var tabs = Tabs(0, 0, 600, 40)
tabs.add("Overview", Panel(0, 40, 600, 360))
tabs.add("Settings", Panel(0, 40, 600, 360))
tabs.add("Analytics", Panel(0, 40, 600, 360))
assert_eq("count", tabs.count, 3)
assert_eq("active init", tabs.active, 0)
tabs.select(2)
assert_eq("active", tabs.active, 2)
assert_true("get_active tab", tabs.get_active() != none)
var tab_changed = false
def on_tab(i):
    tab_changed = true
tabs.on_change(on_tab)
tabs.select(1)
assert_true("tab changed", tab_changed)

# ─── ScrollPanel ──────────────────────────────────────────────────────────────
section("ScrollPanel")
var sp = ScrollPanel(0, 0, 400, 300)
assert_eq("scroll_y init", sp.scroll_y, 0)
sp.set_content_size(400, 1000)
assert_eq("content_h", sp.content_h, 1000)
sp.scroll_to(0, 200)
assert_eq("scroll_y", sp.scroll_y, 200)
sp.scroll_to(0, 2000)
assert_eq("scroll clamped", sp.scroll_y, 700)
sp.add(Label(0, 0, 380, 30, "Item"))

# ─── Spinner ──────────────────────────────────────────────────────────────────
section("Spinner")
var spn = Spinner(10, 10, 32, "default")
assert_eq("size", spn.size, 32)
assert_eq("variant", spn.variant, "default")
assert_eq("angle init", spn.angle, 0.0)
spn.update()
assert_true("angle advanced", spn.angle > 0.0)
spn.set_label("Loading...")
assert_eq("label", spn.label, "Loading...")

# ─── ContextMenu ──────────────────────────────────────────────────────────────
section("ContextMenu")
var cm = ContextMenu()
assert_eq("count init", cm.count, 0)
var cm_action_called = false
def on_cm_action():
    cm_action_called = true
cm.add_item("Cut", on_cm_action)
cm.add_item_with_shortcut("Copy", none, "Ctrl+C")
cm.add_separator()
cm.add_item("Paste", none)
assert_eq("count", cm.count, 4)
cm.show_at(100, 200)
assert_eq("x", cm.x, 100)
assert_eq("y", cm.y, 200)
assert_eq("visible", cm.visible, true)
cm.hide()
assert_eq("hidden", cm.visible, false)

# ─── Form ─────────────────────────────────────────────────────────────────────
section("Form")
var frm = Form(10, 10, 400)
var name_input = TextInput(0, 0, 380, 36, "Full name")
var email_input = TextInput(0, 0, 380, 36, "Email")
var age_input = NumberInput(0, 0, 120, 36, 0.0, 150.0, 1.0)
frm.add_field("name", "Name", name_input)
frm.add_field("email", "Email", email_input)
frm.add_field("age", "Age", age_input)
assert_eq("field count", frm.field_count, 3)
frm.set_required("name")
frm.set_required("email")
name_input.value = "Alice"
email_input.value = "alice@example.com"
age_input.value = 30.0
assert_true("valid", frm.validate())
name_input.value = ""
assert_true("invalid when empty", not frm.validate())
name_input.value = "Alice"
var vals = frm.get_values()
assert_eq("get name", vals["name"], "Alice")
frm.reset()
assert_eq("reset name", frm.get_value("name"), "")

# ─── DataTable ────────────────────────────────────────────────────────────────
section("DataTable")
var dt = DataTable(0, 0, 600, 300)
dt.add_column("id", "ID", 60)
dt.add_column("name", "Name", 200)
dt.add_column("role", "Role", 120)
assert_eq("col count", dt.col_count, 3)
var r1 = {}
r1["id"] = 1
r1["name"] = "Alice"
r1["role"] = "Admin"
var r2 = {}
r2["id"] = 2
r2["name"] = "Bob"
r2["role"] = "User"
var r3 = {}
r3["id"] = 3
r3["name"] = "Carol"
r3["role"] = "Editor"
dt.add_row(r1)
dt.add_row(r2)
dt.add_row(r3)
assert_eq("row count", dt.row_count, 3)
var sel_data = none
def on_dt_select(row):
    sel_data = row
dt.on_select(on_dt_select)
dt.clear_rows()
assert_eq("cleared", dt.row_count, 0)
var rows = [r1, r2, r3]
dt.set_data(rows)
assert_eq("set_data", dt.row_count, 3)

# ─── Accordion ────────────────────────────────────────────────────────────────
section("Accordion")
var acc = Accordion(0, 0, 500)
var pA = Panel(0, 0, 500, 100)
var pB = Panel(0, 0, 500, 150)
var pC = Panel(0, 0, 500, 80)
acc.add("Section A", pA)
acc.add("Section B", pB)
acc.add("Section C", pC)
assert_eq("count", acc.count, 3)
assert_eq("all collapsed", acc.items[0].expanded, false)
acc.expand(1)
assert_eq("section B expanded", acc.items[1].expanded, true)
assert_eq("section A not expanded", acc.items[0].expanded, false)
acc.expand(2)
assert_eq("C expanded", acc.items[2].expanded, true)
assert_eq("B collapsed after single", acc.items[1].expanded, false)
acc.allow_multiple = true
acc.expand(0)
acc.expand(1)
assert_eq("multi A", acc.items[0].expanded, true)
assert_eq("multi B", acc.items[1].expanded, true)
acc.collapse(0)
assert_eq("collapsed A", acc.items[0].expanded, false)
acc.collapse_all()
assert_eq("all collapsed", acc.items[2].expanded, false)
acc.set_pos(10, 20)
assert_eq("set_pos x", acc.x, 10)
acc.hide()
assert_eq("hidden", acc.visible, false)
acc.show()
assert_eq("shown", acc.visible, true)

# ─── RangeSlider ──────────────────────────────────────────────────────────────
section("RangeSlider")
var rs = RangeSlider(10, 10, 300, 0.0, 100.0, 20.0, 80.0)
assert_eq("min", rs.min_val, 0.0)
assert_eq("max", rs.max_val, 100.0)
assert_eq("low", rs.low, 20.0)
assert_eq("high", rs.high, 80.0)
assert_eq("span", rs.span(), 60.0)
rs.set_low(30.0)
assert_eq("set_low", rs.low, 30.0)
rs.set_high(70.0)
assert_eq("set_high", rs.high, 70.0)
rs.set_range(10.0, 90.0)
assert_eq("range low", rs.low, 10.0)
assert_eq("range high", rs.high, 90.0)
rs.set_low(-10.0)
assert_eq("low clamped to min", rs.low, 0.0)
rs.set_high(200.0)
assert_eq("high clamped to max", rs.high, 100.0)
rs.set_high(50.0)
rs.set_low(60.0)
assert_eq("low clamped to high", rs.low, 50.0)
var rs_changed = false
def on_rs_change(e):
    rs_changed = true
rs.on("change", on_rs_change)
rs.set_pos(20, 30)
assert_eq("pos x", rs.rect.x, 20)
rs.set_size(400, 24)
assert_eq("size w", rs.rect.w, 400)
rs.hide()
assert_eq("hidden", rs.visible, false)
rs.show()
rs.disable()
assert_eq("disabled", rs.enabled, false)
rs.enable()
assert_eq("enabled", rs.enabled, true)

# ─── TreeNode / TreeView ──────────────────────────────────────────────────────
section("TreeNode")
var root = TreeNode("Root", "root")
var child1 = TreeNode("Child 1", "c1")
var child2 = TreeNode("Child 2", "c2")
var grandchild = TreeNode("Grandchild", "gc1")
root.add_child(child1)
root.add_child(child2)
child1.add_child(grandchild)
assert_eq("root children", root.child_count, 2)
assert_eq("child1 children", child1.child_count, 1)
assert_eq("grandchild depth", grandchild.depth, 2)
assert_eq("child depth", child1.depth, 1)
assert_true("root has children", root.has_children())
assert_true("child1 has children", child1.has_children())
assert_true("child2 no children", not child2.has_children())
root.expand()
assert_eq("expanded", root.expanded, true)
root.collapse()
assert_eq("collapsed", root.expanded, false)
root.toggle()
assert_eq("toggled", root.expanded, true)
var found = root.find("gc1")
assert_true("found gc1", found != none)
assert_eq("found label", found.label, "Grandchild")
var not_found = root.find("zzz")
assert_eq("not found", not_found, none)

section("TreeView")
var tv = TreeView(0, 0, 300, 400)
tv.add_root(root)
assert_eq("root count", tv.root_count, 1)
var select_called = false
def on_tv_select(node):
    select_called = true
tv.on_select(on_tv_select)
tv.select("c2")
assert_true("selected", tv.selected != none)
assert_eq("selected label", tv.selected.label, "Child 2")
var found2 = tv.find("gc1")
assert_true("tv find", found2 != none)
tv.set_pos(10, 10)
assert_eq("pos x", tv.rect.x, 10)
tv.set_size(400, 500)
assert_eq("size h", tv.rect.h, 500)
tv.hide()
assert_eq("hidden", tv.visible, false)
tv.show()

# ─── TagInput ─────────────────────────────────────────────────────────────────
section("TagInput")
var tagi = TagInput(10, 10, 300, 40, "Add tags...")
assert_eq("placeholder", tagi.placeholder, "Add tags...")
assert_eq("tag count init", tagi.tag_count, 0)
assert_true("add python", tagi.add_tag("python"))
assert_true("add nython", tagi.add_tag("nython"))
assert_true("add ai", tagi.add_tag("ai"))
assert_eq("tag count", tagi.tag_count, 3)
assert_true("has python", tagi.has_tag("python"))
assert_true("no ruby", not tagi.has_tag("ruby"))
assert_true("no dup", not tagi.add_tag("python"))
assert_eq("no dup count", tagi.tag_count, 3)
tagi.remove_tag("nython")
assert_eq("removed", tagi.tag_count, 2)
assert_true("nython gone", not tagi.has_tag("nython"))
tagi.add_tag("ml")
tagi.remove_last()
assert_eq("remove last", tagi.tag_count, 2)
tagi.clear()
assert_eq("cleared", tagi.tag_count, 0)
tagi.disable()
assert_eq("disabled", tagi.enabled, false)
tagi.enable()
var tag_added = false
def on_tag_add(e):
    tag_added = true
tagi.on("add", on_tag_add)
tagi.add_tag("test")
assert_true("add event", tag_added)

# ─── Rating ───────────────────────────────────────────────────────────────────
section("Rating")
var rat = Rating(10, 10, 5, 0.0)
assert_eq("max_stars", rat.max_stars, 5)
assert_eq("value init", rat.value, 0.0)
rat.set_value(3.0)
assert_eq("set_value", rat.value, 3.0)
rat.set_value(7.0)
assert_eq("clamped max", rat.value, 5.0)
rat.set_value(-1.0)
assert_eq("clamped min", rat.value, 0.0)
var rating_changed = 0.0
def on_rating(v):
    rating_changed = v
rat.on_change(on_rating)
rat.set_value(4.0)
rat.set_pos(20, 20)
assert_eq("pos x", rat.x, 20)
rat.hide()
assert_eq("hidden", rat.visible, false)
rat.show()
assert_eq("width", rat.width(), 140)

# ─── Breadcrumb ───────────────────────────────────────────────────────────────
section("Breadcrumb")
var bc = Breadcrumb(10, 10, 30)
bc.add("Home", "/")
bc.add("Products", "/products")
bc.add("Laptop", "/products/laptop")
assert_eq("item count", bc.item_count, 3)
var cur = bc.current()
assert_true("current not none", cur != none)
assert_eq("current label", cur["label"], "Laptop")
bc.set_separator("/")
assert_eq("separator", bc.separator, "/")
var bc_clicked = false
def on_bc_click(v):
    bc_clicked = true
bc.on_click(on_bc_click)
bc.clear()
assert_eq("cleared", bc.item_count, 0)
var cur2 = bc.current()
assert_eq("current empty", cur2, none)
bc.set_pos(20, 20)
assert_eq("pos x", bc.x, 20)
bc.hide()
assert_eq("hidden", bc.visible, false)
bc.show()

# ─── Avatar ───────────────────────────────────────────────────────────────────
section("Avatar")
var av = Avatar(10, 10, 48)
assert_eq("size", av.size, 48)
assert_eq("name init", av.name, "")
av.set_name("Alice Chen")
assert_eq("name", av.name, "Alice Chen")
assert_eq("initials", av.initials(), "AC")
var av2 = Avatar(10, 10, 48)
av2.set_name("Bob")
assert_eq("single name initials", av2.initials(), "B")
var av3 = Avatar(10, 10, 48)
assert_eq("empty initials", av3.initials(), "?")
av.set_status("online")
assert_eq("status", av.status, "online")
av.set_color(Color(100, 150, 200, 255))
assert_true("custom color", av.color != none)
av.set_pos(20, 30)
assert_eq("pos x", av.x, 20)
av.hide()
assert_eq("hidden", av.visible, false)
av.show()

# ─── ProgressRing ─────────────────────────────────────────────────────────────
section("ProgressRing")
var pr = ProgressRing(10, 10, 80, 0.0, 100.0)
assert_eq("size", pr.size, 80)
assert_eq("value init", pr.value, 0.0)
pr.set_value(75.0)
assert_eq("set_value", pr.value, 75.0)
assert_eq("percent", pr.percent(), 75.0)
pr.set_value(150.0)
assert_eq("clamped max", pr.value, 100.0)
pr.set_value(-10.0)
assert_eq("clamped min", pr.value, 0.0)
pr.set_label("Storage")
assert_eq("label", pr.label, "Storage")
pr.set_pos(20, 20)
assert_eq("pos x", pr.x, 20)
pr.hide()
assert_eq("hidden", pr.visible, false)
pr.show()

# ─── Pagination ───────────────────────────────────────────────────────────────
section("Pagination")
var pg = Pagination(10, 10, 20)
assert_eq("total", pg.total_pages, 20)
assert_eq("current init", pg.current_page, 1)
pg.next()
assert_eq("next", pg.current_page, 2)
pg.next()
assert_eq("next2", pg.current_page, 3)
pg.prev()
assert_eq("prev", pg.current_page, 2)
pg.last()
assert_eq("last", pg.current_page, 20)
pg.first()
assert_eq("first", pg.current_page, 1)
pg.go_to(10)
assert_eq("go_to", pg.current_page, 10)
pg.go_to(25)
assert_eq("go_to clamped", pg.current_page, 20)
pg.go_to(0)
assert_eq("go_to min", pg.current_page, 1)
assert_true("has_next", pg.has_next())
pg.last()
assert_true("no next", not pg.has_next())
pg.first()
assert_true("no prev", not pg.has_prev())
var pg_changed = 0
def on_pg_change(p):
    pg_changed = p
pg.on_change(on_pg_change)
pg.go_to(5)
assert_eq("callback", pg_changed, 5)
pg.set_total(50)
assert_eq("set_total", pg.total_pages, 50)
pg.set_pos(20, 20)
assert_eq("pos x", pg.x, 20)

# ─── Stepper ──────────────────────────────────────────────────────────────────
section("Stepper")
var stp = Stepper(0, 0, 600, 80, "horizontal")
stp.add_step("Account", "Create your account")
stp.add_step("Profile", "Set up profile")
stp.add_step("Payment", "Add payment")
stp.add_step("Confirm", "Review and submit")
assert_eq("step count", stp.step_count, 4)
assert_eq("current init", stp.current, 0)
stp.next_step()
assert_eq("next", stp.current, 1)
assert_eq("prev completed", stp.steps[0].completed, true)
stp.next_step()
assert_eq("next2", stp.current, 2)
stp.prev_step()
assert_eq("prev", stp.current, 1)
stp.go_to(3)
assert_eq("go_to", stp.current, 3)
stp.complete_step(3)
assert_eq("completed", stp.steps[3].completed, true)
stp.set_error(2)
assert_eq("error", stp.steps[2].error, true)
stp.reset()
assert_eq("reset current", stp.current, 0)
assert_eq("reset completed", stp.steps[0].completed, false)
assert_eq("reset error", stp.steps[2].error, false)
assert_true("not complete", not stp.is_complete())
var stp_changed = false
def on_stp(i):
    stp_changed = true
stp.on_change(on_stp)
stp.go_to(2)
assert_true("callback", stp_changed)
stp.set_pos(10, 20)
assert_eq("pos x", stp.rect.x, 10)
stp.hide()
assert_eq("hidden", stp.visible, false)
stp.show()

# ─── Drawer ───────────────────────────────────────────────────────────────────
section("Drawer")
var dr = Drawer("left", 280, 1280, 800)
assert_eq("side", dr.side, "left")
assert_eq("w", dr.w, 280)
assert_eq("open init", dr.open, false)
dr.set_title("Settings")
assert_eq("title", dr.title, "Settings")
dr.add(Label(20, 80, 240, 30, "Theme"))
dr.add(Switch(20, 120, "Dark mode"))
assert_eq("child count", dr.child_count, 2)
dr.show()
assert_eq("opened", dr.open, true)
dr.hide()
assert_eq("closed", dr.open, false)
assert_eq("visible stays", dr.visible, true)
dr.toggle()
assert_eq("toggled open", dr.open, true)
dr.toggle()
assert_eq("toggled closed", dr.open, false)
var closed = false
def on_dr_close():
    closed = true
dr.on_close(on_dr_close)
dr.show()
dr.hide()
assert_true("close callback", closed)
var right_dr = Drawer("right", 320, 1280, 800)
var right_rect = right_dr._rect()
assert_eq("right side x", right_rect.x, 960)

# ─── MenuItem / Menu / MenuBar ────────────────────────────────────────────────
section("MenuItem")
var mi = MenuItem("Save", none)
assert_eq("label", mi.label, "Save")
assert_eq("enabled init", mi.enabled, true)
mi.set_shortcut("Ctrl+S")
assert_eq("shortcut", mi.shortcut, "Ctrl+S")
mi.disable()
assert_eq("disabled", mi.enabled, false)
mi.enable()
assert_eq("enabled", mi.enabled, true)

section("Menu")
var menu = Menu("File")
menu.add("New", none)
menu.add("Open", none)
menu.add_separator()
menu.add("Save", none)
menu.add("Save As", none)
menu.add_separator()
menu.add("Quit", none)
assert_eq("item count", menu.item_count, 7)
assert_eq("label", menu.label, "File")
assert_eq("sep is sep", menu.items[2].separator, true)

section("MenuBar")
def on_new(): pass
def on_open(): pass
def on_save(): pass
def on_undo(): pass
def on_redo(): pass
var mb = MenuBar(1280)
var file_menu = Menu("File")
file_menu.add("New", on_new)
file_menu.add("Open", on_open)
file_menu.add_separator()
file_menu.add("Save", on_save)
var edit_menu = Menu("Edit")
edit_menu.add("Undo", on_undo)
edit_menu.add("Redo", on_redo)
var view_menu = Menu("View")
view_menu.add("Zoom In", none)
view_menu.add("Zoom Out", none)
mb.add_menu(file_menu)
mb.add_menu(edit_menu)
mb.add_menu(view_menu)
assert_eq("menu count", mb.menu_count, 3)
assert_eq("h", mb.h, 30)
assert_eq("active init", mb.active_menu, -1)
mb.close_all()
assert_eq("all closed", mb.active_menu, -1)
assert_eq("mb type", type(mb), "MenuBar")

# ─── StatusBar ────────────────────────────────────────────────────────────────
section("StatusBar")
var sb = StatusBar(1280, 800)
assert_eq("h", sb.h, 24)
sb.add_left("Ready", "✓")
sb.add_left("Ln 1, Col 1", "")
sb.add_right("UTF-8", "")
sb.add_right("Python", "")
assert_eq("left count", sb.left_count, 2)
assert_eq("right count", sb.right_count, 2)
sb.set_left(0, "Modified")
assert_eq("set_left", sb.left_items[0]["text"], "Modified")
sb.set_right(0, "ASCII")
assert_eq("set_right", sb.right_items[0]["text"], "ASCII")
sb.clear_left()
assert_eq("cleared left", sb.left_count, 0)
sb.clear_right()
assert_eq("cleared right", sb.right_count, 0)
assert_eq("sb type", type(sb), "StatusBar")

# ─── Notification / NotificationCenter ───────────────────────────────────────
section("Notification")
var notif = Notification("Update Available", "v2.0 is ready", "info", 5000)
assert_eq("title", notif.title, "Update Available")
assert_eq("body", notif.body, "v2.0 is ready")
assert_eq("type", notif.type, "info")
assert_eq("duration", notif.duration_ms, 5000)
assert_eq("read init", notif.read, false)
assert_eq("dismissed init", notif.dismissed, false)
assert_true("id not empty", notif.id != "")
assert_true("not expired", not notif.is_expired())
notif.mark_read()
assert_eq("marked read", notif.read, true)
notif.dismiss()
assert_eq("dismissed", notif.dismissed, true)
var action_called = false
def notif_action():
    action_called = true
notif.set_action("View", notif_action)
assert_eq("action label", notif.action_label, "View")

section("NotificationCenter")
var nc = NotificationCenter(1280, 800)
assert_eq("count init", nc.count, 0)
assert_eq("unread init", nc.unread, 0)
var n1 = nc.success("Saved!", "Your file was saved successfully.")
var n2 = nc.error("Failed", "Could not connect to server.")
var n3 = nc.warning("Disk Space", "Less than 10% free.")
var n4 = nc.info("Update", "A new version is available.")
assert_eq("count 4", nc.count, 4)
assert_eq("unread 4", nc.unread, 4)
assert_true("n1 not none", n1 != none)
assert_eq("n1 type", n1.type, "success")
assert_eq("n2 type", n2.type, "error")
nc.dismiss(n1.id)
nc.update()
assert_true("count after dismiss", nc.count <= 3)
nc.dismiss_all()
nc.update()
assert_eq("count after dismiss all", nc.count, 0)
nc.hide()
assert_eq("hidden", nc.visible, false)
nc.show()

# ─── ListView ─────────────────────────────────────────────────────────────────
section("ListView")
var lv = ListView(0, 0, 400, 500)
lv.add_item("Alice Chen", "Product Manager", "alice")
lv.add_item("Bob Smith", "Engineer", "bob")
lv.add_item("Carol Davis", "Designer", "carol")
lv.add_item("Dave Wilson", "QA", "dave")
lv.add_item("Eve Martinez", "DevOps", "eve")
assert_eq("item count", lv.item_count, 5)
assert_eq("selected init", lv.selected, -1)
lv.select(2)
assert_eq("selected", lv.selected, 2)
var sel = lv.get_selected()
assert_true("get_selected", sel != none)
assert_eq("selected label", sel["label"], "Carol Davis")
assert_eq("selected value", sel["value"], "carol")
var sel_called = false
def on_lv_select(item):
    sel_called = true
lv.on_select(on_lv_select)
lv.select(0)
assert_true("select callback", sel_called)
lv.set_item_height(48)
assert_eq("item height", lv.item_h, 48)
lv.add_item_with_icon("Frank Lee", "CEO", "frank", "👤")
assert_eq("icon item count", lv.item_count, 6)
assert_eq("icon item icon", lv.items[5]["icon"], "👤")
lv.clear()
assert_eq("cleared", lv.item_count, 0)
assert_eq("selected cleared", lv.selected, -1)
lv.set_pos(10, 10)
assert_eq("pos x", lv.rect.x, 10)
lv.set_size(500, 600)
assert_eq("size w", lv.rect.w, 500)
lv.hide()
assert_eq("hidden", lv.visible, false)
lv.show()
lv.disable()
assert_eq("disabled", lv.enabled, false)
lv.enable()
assert_eq("enabled", lv.enabled, true)

# ─── v7 + Wave 3 Beautiful Widgets Tests ──────────────────────────────────────

# ─── GlassCard ────────────────────────────────────────────────────────────────
section("GlassCard")
var gc = GlassCard(10, 10, 320, 200)
assert_eq("radius", gc.radius, 20)
assert_eq("glow init", gc.glow, true)
gc.set_title("Revenue")
gc.set_subtitle("Monthly overview")
assert_eq("title", gc.title, "Revenue")
assert_eq("subtitle", gc.subtitle, "Monthly overview")
gc.set_accent(Color(255, 100, 50, 255))
assert_eq("accent r", gc.accent.r, 255)
var gc_lbl = Label(20, 80, 280, 30, "$ 42,000")
gc.add(gc_lbl)
assert_eq("child count", gc.child_count, 1)
gc.set_pos(50, 50)
assert_eq("pos x", gc.rect.x, 50)
gc.set_size(400, 240)
assert_eq("size w", gc.rect.w, 400)
gc.hide()
assert_eq("hidden", gc.visible, false)
gc.show()
assert_eq("shown", gc.visible, true)

# ─── FloatingActionButton ─────────────────────────────────────────────────────
section("FloatingActionButton")
var fab = FloatingActionButton(100, 100, "+", 56)
assert_eq("icon", fab.icon, "+")
assert_eq("size", fab.size, 56)
assert_eq("r", fab.r, 28)
assert_eq("enabled init", fab.enabled, true)
fab.set_color(Color(52, 199, 89, 255))
assert_eq("color r", fab.color.r, 52)
assert_eq("shadow_color r", fab.shadow_color.r, 52)
fab.set_label("Create")
assert_eq("label", fab.label, "Create")
assert_eq("extended", fab.extended, true)
fab.set_label("")
assert_eq("not extended", fab.extended, false)
var fab_clicked = false
def on_fab_click(e):
    fab_clicked = true
fab.on("click", on_fab_click)
var fev = Event("click")
fab.emit(fev)
assert_true("clicked", fab_clicked)
fab.disable()
assert_eq("disabled", fab.enabled, false)
fab.enable()
fab.set_pos(200, 200)
assert_eq("pos cx", fab.cx, 200)
fab.hide()
assert_eq("hidden", fab.visible, false)
fab.show()

# ─── ColorPicker ──────────────────────────────────────────────────────────────
section("ColorPicker")
var cp = ColorPicker(10, 10, 200)
assert_eq("hue init", cp.hue, 0.0)
assert_eq("saturation init", cp.saturation, 1.0)
assert_eq("alpha init", cp.alpha, 1.0)
cp.set_hue(0.5)
assert_eq("hue set", cp.hue, 0.5)
cp.set_saturation(0.8)
assert_eq("sat set", cp.saturation, 0.8)
cp.set_value_field(0.9)
assert_eq("val set", cp.value, 0.9)
var picked = cp.get_color()
assert_true("color not none", picked != none)
assert_true("color is Color", type(picked) == "Color")
var hex = cp.get_hex()
assert_true("hex starts #", string_startswith(hex, "#"))
assert_eq("hex length", len(hex), 7)
var changed = false
def on_cp_change(c):
    changed = true
cp.on_change(on_cp_change)
cp.set_hue(0.3)
assert_true("change callback", changed)
cp.set_pos(20, 20)
assert_eq("pos x", cp.x, 20)
cp.hide()
assert_eq("hidden", cp.visible, false)
cp.show()
cp.disable()
assert_eq("disabled", cp.enabled, false)
cp.enable()

# ─── ChartSeries ──────────────────────────────────────────────────────────────
section("ChartSeries")
var cs = ChartSeries("Revenue", [10.0, 25.0, 18.0, 42.0, 35.0], Color(99, 102, 241, 255))
assert_eq("name", cs.name, "Revenue")
assert_eq("data len", len(cs.data), 5)
assert_eq("color b", cs.color.b, 241)
assert_eq("line_w", cs.line_w, 2)
assert_eq("show_dots", cs.show_dots, true)
assert_eq("fill", cs.fill, true)
cs.line_w = 3
assert_eq("line_w set", cs.line_w, 3)
cs.show_dots = false
assert_eq("no dots", cs.show_dots, false)

# ─── LineChart ────────────────────────────────────────────────────────────────
section("LineChart")
var lc = LineChart(10, 10, 500, 300)
assert_eq("rect w", lc.rect.w, 500)
assert_eq("series init", lc.series_count, 0)
lc.set_title("Sales 2025")
assert_eq("title", lc.title, "Sales 2025")
var s1 = ChartSeries("Q1", [10.0, 30.0, 25.0, 45.0, 40.0, 55.0], Color(99, 102, 241, 255))
var s2 = ChartSeries("Q2", [5.0, 20.0, 35.0, 30.0, 50.0, 48.0], Color(220, 100, 255, 255))
lc.add_series(s1)
lc.add_series(s2)
assert_eq("series count", lc.series_count, 2)
lc.set_x_labels(["Jan", "Feb", "Mar", "Apr", "May", "Jun"])
assert_eq("x_label_count", lc.x_label_count, 6)
lc.update()
assert_true("anim advances", lc.anim_progress > 0.0)
var pa = lc._plot_area()
assert_eq("plot area x", pa.x, lc.rect.x + lc.padding_left)
var mn = lc._min_val()
var mx = lc._max_val()
assert_true("min < max", mn < mx)
lc.set_pos(20, 20)
assert_eq("pos x", lc.rect.x, 20)
lc.set_size(600, 350)
assert_eq("size h", lc.rect.h, 350)
lc.hide()
assert_eq("hidden", lc.visible, false)
lc.show()

# ─── BarChart ─────────────────────────────────────────────────────────────────
section("BarChart")
var bc = BarChart(10, 10, 480, 300)
assert_eq("bar_count init", bc.bar_count, 0)
assert_eq("auto_max", bc.auto_max, true)
bc.set_title("Monthly Revenue")
assert_eq("title", bc.title, "Monthly Revenue")
bc.add_bar("Jan", 120.0, Color(99, 102, 241, 255))
bc.add_bar("Feb", 85.0, Color(220, 100, 255, 255))
bc.add_bar("Mar", 200.0, Color(52, 199, 89, 255))
bc.add_bar("Apr", 165.0, Color(255, 149, 0, 255))
assert_eq("bar_count", bc.bar_count, 4)
assert_eq("auto max", bc.max_value, 200.0)
bc.set_max(300.0)
assert_eq("max set", bc.max_value, 300.0)
assert_eq("auto false", bc.auto_max, false)
bc.update()
assert_true("anim advances", bc.anim_progress > 0.0)
bc.set_pos(20, 20)
assert_eq("pos x", bc.rect.x, 20)
bc.set_size(600, 400)
assert_eq("size w", bc.rect.w, 600)
bc.hide()
assert_eq("hidden", bc.visible, false)
bc.show()

# ─── Gauge ────────────────────────────────────────────────────────────────────
section("Gauge")
var gauge = Gauge(10, 10, 200, 0, 100, 0)
assert_eq("size", gauge.size, 200)
assert_eq("min", gauge.min_val, 0)
assert_eq("max", gauge.max_val, 100)
assert_eq("value init", gauge.value, 0)
gauge.set_value(75)
assert_eq("value set", gauge.value, 75)
gauge.set_value(150)
assert_eq("clamped max", gauge.value, 100)
gauge.set_value(-10)
assert_eq("clamped min", gauge.value, 0)
gauge.set_label("Speed")
assert_eq("label", gauge.label, "Speed")
gauge.set_unit("km/h")
assert_eq("unit", gauge.unit, "km/h")
gauge.add_zone(0.0, 0.33, Color(52, 199, 89, 255))
gauge.add_zone(0.33, 0.66, Color(255, 149, 0, 255))
gauge.add_zone(0.66, 1.0, Color(255, 59, 48, 255))
assert_eq("zone count", gauge.zone_count, 3)
var ang = gauge._val_to_angle(50)
assert_true("angle mid", ang > gauge.start_angle and ang < gauge.start_angle + gauge.sweep_angle)
gauge.update()
gauge.set_pos(20, 20)
assert_eq("pos x", gauge.x, 20)
gauge.hide()
assert_eq("hidden", gauge.visible, false)
gauge.show()

# ─── CalendarWidget ───────────────────────────────────────────────────────────
section("CalendarWidget")
var cal = CalendarWidget(10, 10, 350, 360)
cal.set_date(2025, 6)
assert_eq("year", cal.year, 2025)
assert_eq("month", cal.month, 6)
cal.set_today(2025, 6, 15)
assert_eq("today", cal.today_day, 15)
cal.add_event(10, "Team Meeting")
cal.add_event(25, "Release")
assert_true("has event 10", cal.has_event(10))
assert_true("has event 25", cal.has_event(25))
assert_true("no event 5", not cal.has_event(5))
var days = cal._days_in_month(2025, 2)
assert_eq("Feb 2025", days, 28)
var days_leap = cal._days_in_month(2024, 2)
assert_eq("Feb 2024 leap", days_leap, 29)
assert_eq("Jan days", cal._days_in_month(2025, 1), 31)
assert_eq("Apr days", cal._days_in_month(2025, 4), 30)
var nav_called = false
def on_cal_nav(y, m):
    nav_called = true
cal.on_navigate(on_cal_nav)
cal.prev_month()
assert_eq("prev month", cal.month, 5)
assert_true("nav callback", nav_called)
cal.next_month()
assert_eq("next month", cal.month, 6)
cal.next_month()
cal.next_month()
cal.next_month()
cal.next_month()
cal.next_month()
cal.next_month()
cal.next_month()
assert_eq("wrap to next year", cal.year, 2026)
var sel_called = false
def on_cal_select(y, m, d):
    sel_called = true
cal.on_select(on_cal_select)
cal.set_pos(20, 20)
assert_eq("pos x", cal.rect.x, 20)
cal.hide()
assert_eq("hidden", cal.visible, false)
cal.show()

# ─── SkeletonLoader ───────────────────────────────────────────────────────────
section("SkeletonLoader")
var sk = SkeletonLoader(10, 10, 300, 400)
assert_eq("block count init", sk.block_count, 0)
sk.add_block(0, 0, 300, 180, 12)
sk.add_block(0, 196, 180, 16, 8)
assert_eq("block count", sk.block_count, 2)
var sk2 = SkeletonLoader(10, 10, 280, 400)
sk2.preset_card()
assert_eq("card preset blocks", sk2.block_count, 5)
var sk3 = SkeletonLoader(10, 10, 280, 80)
sk3.preset_list_item()
assert_eq("list item blocks", sk3.block_count, 3)
var sk4 = SkeletonLoader(10, 10, 280, 200)
sk4.preset_profile()
assert_eq("profile blocks", sk4.block_count, 6)
var sk5 = SkeletonLoader(10, 10, 280, 120)
sk5.preset_text(4)
assert_eq("text 4 lines", sk5.block_count, 4)
sk.update()
assert_true("shimmer advances", sk.shimmer_x > 0.0)
sk.set_pos(20, 20)
assert_eq("pos x", sk.rect.x, 20)
sk.hide()
assert_eq("hidden", sk.visible, false)
sk.show()

# ─── Timeline ─────────────────────────────────────────────────────────────────
section("Timeline")
var tl = Timeline(10, 10, 400)
assert_eq("event count init", tl.event_count, 0)
tl.add_event("Project Started", "Kickoff meeting held", "Jan 1, 2025", Color(99, 102, 241, 255), "🚀")
tl.add_event("MVP Released", "First public version", "Mar 15, 2025", Color(52, 199, 89, 255), "✅")
tl.add_event("Bug Fixed", "Critical hotfix deployed", "Apr 2, 2025", Color(255, 149, 0, 255), "🐛")
assert_eq("event count", tl.event_count, 3)
tl.add_tagged_event("v2.0 Launch", "Major update", "Jun 1, 2025", Color(220, 100, 255, 255), "🎉", "milestone")
assert_eq("tagged event", tl.event_count, 4)
assert_eq("tag", tl.events[3].tag, "milestone")
assert_eq("first title", tl.events[0].title, "Project Started")
assert_eq("first icon", tl.events[0].icon, "🚀")
var total_h = tl.total_height()
assert_eq("total_height", total_h, 4 * (tl.min_item_h + tl.item_gap))
var tl_click = false
def on_tl_click(i, ev):
    tl_click = true
tl.on_click(on_tl_click)
tl.set_pos(20, 20)
assert_eq("pos x", tl.x, 20)
tl.hide()
assert_eq("hidden", tl.visible, false)
tl.show()

# ─── PieChart ─────────────────────────────────────────────────────────────────
section("PieChart")
var pie = PieChart(10, 10, 280)
assert_eq("seg count init", pie.seg_count, 0)
assert_eq("donut", pie.donut, true)
assert_eq("anim_progress init", pie.anim_progress, 0.0)
pie.set_title("Market Share")
assert_eq("title", pie.title, "Market Share")
pie.set_center("Total", "$1.2M")
assert_eq("center label", pie.center_label, "Total")
assert_eq("center value", pie.center_value, "$1.2M")
pie.add_segment("Product A", 45.0, Color(99, 102, 241, 255))
pie.add_segment("Product B", 30.0, Color(52, 199, 89, 255))
pie.add_segment("Product C", 25.0, Color(255, 149, 0, 255))
assert_eq("seg count", pie.seg_count, 3)
var tot = pie._total()
assert_eq("total", tot, 100.0)
pie.update()
assert_true("anim advances", pie.anim_progress > 0.0)
pie.set_pos(20, 20)
assert_eq("pos x", pie.x, 20)
pie.hide()
assert_eq("hidden", pie.visible, false)
pie.show()

# ─── KanbanCard ───────────────────────────────────────────────────────────────
section("KanbanCard")
var kc = KanbanCard("card-1", "Implement login", "Add OAuth2 support")
assert_eq("id", kc.id, "card-1")
assert_eq("title", kc.title, "Implement login")
assert_eq("priority init", kc.priority, "normal")
kc.set_priority("high")
assert_eq("priority", kc.priority, "high")
kc.set_progress(60)
assert_eq("progress", kc.progress, 60)
kc.set_assignee("Alice")
assert_eq("assignee", kc.assignee, "Alice")
kc.set_due("Dec 15")
assert_eq("due", kc.due, "Dec 15")
kc.add_tag("backend")
kc.add_tag("auth")
assert_eq("tag count", kc.tag_count, 2)
assert_eq("tag 0", kc.tags[0], "backend")

# ─── KanbanColumn ─────────────────────────────────────────────────────────────
section("KanbanColumn")
var col = KanbanColumn("todo", "To Do", Color(99, 102, 241, 255))
assert_eq("id", col.id, "todo")
assert_eq("title", col.title, "To Do")
assert_eq("card count init", col.card_count, 0)
var kc1 = KanbanCard("c1", "Task A", "Description A")
var kc2 = KanbanCard("c2", "Task B", "Description B")
var kc3 = KanbanCard("c3", "Task C", "Description C")
col.add_card(kc1)
col.add_card(kc2)
col.add_card(kc3)
assert_eq("card count", col.card_count, 3)
col.remove_card("c2")
assert_eq("after remove", col.card_count, 2)
assert_eq("remaining card 0", col.cards[0].id, "c1")
assert_eq("remaining card 1", col.cards[1].id, "c3")

# ─── KanbanBoard ──────────────────────────────────────────────────────────────
section("KanbanBoard")
var kb = KanbanBoard(10, 10, 800, 600)
kb.set_title("Sprint 42")
assert_eq("title", kb.title, "Sprint 42")
var col_todo = KanbanColumn("todo", "To Do", Color(99, 102, 241, 255))
var col_wip = KanbanColumn("wip", "In Progress", Color(255, 149, 0, 255))
var col_done = KanbanColumn("done", "Done", Color(52, 199, 89, 255))
var ka = KanbanCard("ka", "Feature A", "Desc A")
var kb2 = KanbanCard("kb", "Feature B", "Desc B")
var kc_card = KanbanCard("kc", "Bug Fix", "Desc C")
col_todo.add_card(ka)
col_todo.add_card(kb2)
col_wip.add_card(kc_card)
kb.add_column(col_todo)
kb.add_column(col_wip)
kb.add_column(col_done)
assert_eq("col count", kb.col_count, 3)
assert_eq("total cards", kb.total_cards(), 3)
var got_col = kb.get_column("wip")
assert_true("get column", got_col != none)
assert_eq("column title", got_col.title, "In Progress")
var not_col = kb.get_column("xxx")
assert_eq("get missing col", not_col, none)
var moved = kb.move_card("ka", "todo", "done")
assert_eq("move result", moved, true)
assert_eq("todo after move", col_todo.card_count, 1)
assert_eq("done after move", col_done.card_count, 1)
var bad_move = kb.move_card("zzz", "todo", "done")
assert_eq("bad move", bad_move, false)
kb.set_pos(20, 20)
assert_eq("pos x", kb.rect.x, 20)
kb.set_size(1024, 700)
assert_eq("size w", kb.rect.w, 1024)
kb.hide()
assert_eq("hidden", kb.visible, false)
kb.show()

# ─── HeatMap ──────────────────────────────────────────────────────────────────
section("HeatMap")
var hm = HeatMap(10, 10, 7, 4, 20, 3)
assert_eq("cols", hm.cols, 7)
assert_eq("rows", hm.rows, 4)
assert_eq("data size", len(hm.data), 28)
hm.set_cell(0, 0, 5.0)
hm.set_cell(3, 2, 10.0)
hm.set_cell(6, 3, 8.0)
assert_eq("max val", hm.max_val, 10.0)
hm.set_col_labels(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])
hm.set_row_labels(["W1", "W2", "W3", "W4"])
assert_eq("col labels", hm.col_label_count, 7)
assert_eq("row labels", hm.row_label_count, 4)
hm.set_palette(Color(30, 32, 44, 255), Color(99, 102, 241, 255))
assert_eq("palette high r", hm.colors_high.r, 99)
hm.set_title("Activity")
assert_eq("title", hm.title, "Activity")
var data28 = []
var dfi = 0
while dfi < 28:
    data28 = data28 + [float(dfi % 10)]
    dfi = dfi + 1
hm.set_data(data28)
assert_eq("data set len", len(hm.data), 28)
hm.update()
assert_eq("anim col advances", hm.anim_col, 1)
hm.set_pos(20, 20)
assert_eq("pos x", hm.x, 20)
hm.hide()
assert_eq("hidden", hm.visible, false)
hm.show()
var cc = hm._cell_color(5.0)
assert_true("cell color is Color", type(cc) == "Color")

# ─── AudioWaveform ────────────────────────────────────────────────────────────
section("AudioWaveform")
var aw = AudioWaveform(10, 10, 400, 80)
assert_eq("sample count init", aw.sample_count, 0)
assert_eq("playhead init", aw.playhead, 0.0)
assert_eq("playing init", aw.playing, false)
var samples = []
var awi = 0
while awi < 100:
    samples = samples + [float((awi % 10 + 1)) / 10.0]
    awi = awi + 1
aw.set_samples(samples)
assert_eq("sample count", aw.sample_count, 100)
aw.set_playhead(0.5)
assert_eq("playhead", aw.playhead, 0.5)
aw.set_playhead(-0.1)
assert_eq("clamped low", aw.playhead, 0.0)
aw.set_playhead(1.5)
assert_eq("clamped high", aw.playhead, 1.0)
aw.set_time_display("1:23", "4:56")
assert_eq("current", aw.current_str, "1:23")
assert_eq("duration", aw.duration_str, "4:56")
aw.set_title("Track 01")
assert_eq("title", aw.title, "Track 01")
aw.play()
assert_eq("playing", aw.playing, true)
aw.pause()
assert_eq("paused", aw.playing, false)
aw.update()
assert_true("anim advances", aw.anim_t > 0.0)
var seek_val = -1.0
def on_seek(t):
    seek_val = t
aw.on_seek(on_seek)
aw.set_pos(20, 20)
assert_eq("pos x", aw.rect.x, 20)
aw.set_size(600, 100)
assert_eq("size w", aw.rect.w, 600)
aw.hide()
assert_eq("hidden", aw.visible, false)
aw.show()
assert_eq("aw type", type(aw), "AudioWaveform")

# ─── Spotlight ────────────────────────────────────────────────────────────────
section("Spotlight")
var sp = Spotlight(1280, 800)
assert_eq("visible init", sp.visible, false)
assert_eq("item count init", sp.item_count, 0)
sp.register("new-file", "New File", "File", "📄", "Ctrl+N")
sp.register("save", "Save", "File", "💾", "Ctrl+S")
sp.register("open", "Open", "File", "📂", "Ctrl+O")
sp.register("undo", "Undo", "Edit", "↩", "Ctrl+Z")
sp.register("redo", "Redo", "Edit", "↪", "Ctrl+Y")
sp.register("settings", "Settings", "App", "⚙", "Ctrl+,")
assert_eq("item count", sp.item_count, 6)
sp.open()
assert_eq("opened", sp.visible, true)
assert_eq("query cleared", sp.query, "")
assert_eq("all results", sp.result_count, 6)
sp.query = "fil"
sp._refresh()
assert_true("filtered results", sp.result_count > 0)
assert_true("filtered less than total", sp.result_count < 6)
sp.query = ""
sp._refresh()
assert_eq("all results again", sp.result_count, 6)
sp.close()
assert_eq("closed", sp.visible, false)
sp.toggle()
assert_eq("toggled open", sp.visible, true)
sp.toggle()
assert_eq("toggled closed", sp.visible, false)
var selected_id = ""
def on_sp_select(item):
    selected_id = item.id
sp.on_select(on_sp_select)
sp.open()
sp.selected = 0
sp._execute()
assert_eq("executed", sp.visible, false)
assert_eq("recents", sp.recent_count, 1)
var item1 = sp.items[0]
assert_true("item matches empty", item1.matches(""))
assert_true("item matches label", item1.matches("new"))
assert_true("item matches category", item1.matches("file"))
assert_true("item no match", not item1.matches("xyz"))

# ─── NotificationBell ─────────────────────────────────────────────────────────
section("NotificationBell")
var nb = NotificationBell(100, 40, 40)
assert_eq("unread init", nb.unread, 0)
assert_eq("item count init", nb.item_count, 0)
assert_eq("panel closed", nb.panel_open, false)
nb.add_notification("New Message", "Alice sent you a message", "info")
nb.add_notification("Build Failed", "CI pipeline error on main", "error")
nb.add_notification("Deployment Done", "v2.1 is live", "success")
assert_eq("item count", nb.item_count, 3)
assert_eq("unread count", nb.unread, 3)
assert_eq("wiggle active", nb.wiggle_active, true)
nb.mark_all_read()
assert_eq("unread cleared", nb.unread, 0)
assert_eq("items still exist", nb.item_count, 3)
var bell_opened = false
def on_bell_open():
    bell_opened = true
nb.on_open(on_bell_open)
nb.update()
nb.set_pos(200, 50)
assert_eq("pos cx", nb.cx, 200)
var tc = nb._type_color("success")
assert_eq("success green", tc.r, 52)
var tc2 = nb._type_color("error")
assert_eq("error red", tc2.r, 255)
var tc3 = nb._type_color("info")
assert_eq("info blue", tc3.r, 99)
nb.hide()
assert_eq("hidden", nb.visible, false)
nb.show()

# ─── GradientButton ───────────────────────────────────────────────────────────
section("GradientButton")
var gb = GradientButton(10, 10, 160, 44, "Deploy Now")
assert_eq("label", gb.label, "Deploy Now")
assert_eq("radius", gb.radius, 12)
assert_eq("disabled init", gb.disabled, false)
gb.set_gradient(Color(99, 102, 241, 255), Color(168, 85, 247, 255))
assert_eq("color_a r", gb.color_a.r, 99)
assert_eq("color_b b", gb.color_b.b, 247)
gb.set_icon("🚀")
assert_eq("icon", gb.icon, "🚀")
gb.set_radius(20)
assert_eq("radius set", gb.radius, 20)
gb.disable()
assert_eq("disabled", gb.disabled, true)
gb.enable()
assert_eq("enabled", gb.disabled, false)
var gb_clicked = false
def on_gb_click(e):
    gb_clicked = true
gb.on("click", on_gb_click)
var gev = Event("click")
gb.emit(gev)
assert_true("clicked", gb_clicked)
gb.update()
gb.set_pos(20, 20)
assert_eq("pos x", gb.rect.x, 20)
gb.set_size(200, 52)
assert_eq("size w", gb.rect.w, 200)
gb.hide()
assert_eq("hidden", gb.visible, false)
gb.show()

# ─── AnimatedCounter ──────────────────────────────────────────────────────────
section("AnimatedCounter")
var ac = AnimatedCounter(10, 10, 200, 100, "Total Revenue")
assert_eq("label", ac.label, "Total Revenue")
assert_eq("target init", ac.target, 0.0)
assert_eq("history init", ac.history_count, 0)
ac.set_prefix("$")
assert_eq("prefix", ac.prefix, "$")
ac.set_suffix(" USD")
assert_eq("suffix", ac.suffix, " USD")
ac.set_decimals(2)
assert_eq("decimals", ac.decimals, 2)
ac.set_value(1000000.0)
assert_eq("target", ac.target, 1000000.0)
assert_eq("delta", ac.delta, 1000000.0)
assert_eq("history 1", ac.history_count, 1)
ac.set_value(1250000.0)
assert_eq("delta 2", ac.delta, 250000.0)
assert_eq("history 2", ac.history_count, 2)
var fmt = ac._format(1234567.0)
assert_true("comma format", string_contains(fmt, ","))
assert_true("has prefix", string_startswith(fmt, "$"))
ac.update()
assert_true("display advances", ac.display > 0.0)
var overflow_counter = AnimatedCounter(0, 0, 200, 100, "test")
overflow_counter.history_max = 5
var oi = 0
while oi < 8:
    overflow_counter.set_value(float(oi * 10))
    oi = oi + 1
assert_eq("history capped", overflow_counter.history_count, 5)
ac.set_pos(20, 20)
assert_eq("pos x", ac.rect.x, 20)
ac.set_size(280, 120)
assert_eq("size h", ac.rect.h, 120)
ac.hide()
assert_eq("hidden", ac.visible, false)
ac.show()

# ─── SplitPane ────────────────────────────────────────────────────────────────
section("SplitPane")
var spl = SplitPane(0, 0, 800, 600, "horizontal")
assert_eq("split init", spl.split, 0.5)
assert_eq("orientation", spl.orientation, "horizontal")
spl.set_split(0.3)
assert_eq("split set", spl.split, 0.3)
spl.set_split(0.05)
assert_eq("split min clamp", spl.split, spl.min_split)
spl.set_split(0.95)
assert_eq("split max clamp", spl.split, spl.max_split)
spl.set_split(0.5)
var left_pane = Panel(0, 0, 100, 100)
var right_pane = Panel(0, 0, 100, 100)
spl.set_panes(left_pane, right_pane)
assert_eq("pane a set", spl.pane_a != none, true)
assert_eq("pane b set", spl.pane_b != none, true)
assert_eq("left pane x", left_pane.rect.x, 0)
assert_eq("right pane x", right_pane.rect.x, 403)
assert_eq("left pane w", left_pane.rect.w, 397)
spl.set_split(0.25)
assert_eq("resized left w", left_pane.rect.w, 197)
var dr = spl._divider_rect()
assert_eq("divider y", dr.y, 0)
assert_eq("divider h", dr.h, 600)
var resize_called = false
def on_spl_resize(ratio):
    resize_called = true
spl.on_resize(on_spl_resize)
var vspl = SplitPane(0, 0, 600, 400, "vertical")
vspl.set_split(0.4)
var top_pane = Panel(0, 0, 100, 100)
var bot_pane = Panel(0, 0, 100, 100)
vspl.set_panes(top_pane, bot_pane)
assert_eq("top y", top_pane.rect.y, 0)
assert_eq("bot y", bot_pane.rect.y, 163)
spl.set_pos(10, 10)
assert_eq("pos x", spl.rect.x, 10)
spl.set_size(1000, 700)
assert_eq("size w", spl.rect.w, 1000)
spl.hide()
assert_eq("hidden", spl.visible, false)
spl.show()

# ─── Wave 4 Tests ─────────────────────────────────────────────────────────────

# ─── RadarSeries ──────────────────────────────────────────────────────────────
section("RadarSeries")
var rs = RadarSeries("Strength", [0.8, 0.6, 0.9, 0.4, 0.7], Color(99, 102, 241, 255))
assert_eq("name", rs.name, "Strength")
assert_eq("data len", len(rs.values), 5)
assert_eq("fill_alpha", rs.fill_alpha, 45)
assert_eq("show_dots", rs.show_dots, true)
rs.line_w = 3
assert_eq("line_w", rs.line_w, 3)

# ─── RadarChart ───────────────────────────────────────────────────────────────
section("RadarChart")
var rc = RadarChart(300, 300, 180)
assert_eq("cx", rc.cx, 300)
assert_eq("radius", rc.radius, 180)
assert_eq("axis_count init", rc.axis_count, 0)
assert_eq("series_count init", rc.series_count, 0)
rc.set_title("Skills")
assert_eq("title", rc.title, "Skills")
rc.add_axis("Speed")
rc.add_axis("Power")
rc.add_axis("Defense")
rc.add_axis("Magic")
rc.add_axis("Luck")
rc.add_axis("Stamina")
assert_eq("axis_count", rc.axis_count, 6)
var rs1 = RadarSeries("Hero", [0.9, 0.7, 0.8, 0.5, 0.6, 1.0], Color(99, 102, 241, 255))
var rs2 = RadarSeries("Mage", [0.4, 0.3, 0.5, 1.0, 0.8, 0.6], Color(220, 100, 255, 255))
rc.add_series(rs1)
rc.add_series(rs2)
assert_eq("series_count", rc.series_count, 2)
rc.update()
assert_true("anim advances", rc.anim_progress > 0.0)
var pt = rc._axis_point(0, 100)
assert_true("pt is list", type(pt) == "list")
assert_eq("pt len", len(pt), 2)
rc.set_pos(400, 400)
assert_eq("cx updated", rc.cx, 400)
rc.set_radius(200)
assert_eq("radius updated", rc.radius, 200)
rc.hide()
assert_eq("hidden", rc.visible, false)
rc.show()
assert_eq("shown", rc.visible, true)

# ─── SideNavItem ──────────────────────────────────────────────────────────────
section("SideNavItem")
var sni = SideNavItem("dashboard", "Dashboard", "🏠")
assert_eq("id", sni.id, "dashboard")
assert_eq("label", sni.label, "Dashboard")
assert_eq("icon", sni.icon, "🏠")
assert_eq("badge init", sni.badge, 0)
assert_eq("active init", sni.active, false)
sni.set_badge(5)
assert_eq("badge", sni.badge, 5)
sni.set_divider()
assert_eq("divider", sni.divider_before, true)

# ─── SideNav ──────────────────────────────────────────────────────────────────
section("SideNav")
var sn = SideNav(0, 0, 600)
assert_eq("w init", sn.w, 220)
assert_eq("collapsed init", sn.collapsed, false)
assert_eq("item_count init", sn.item_count, 0)
sn.add_item("home", "Home", "🏠")
sn.add_item("analytics", "Analytics", "📊")
sn.add_item("users", "Users", "👥")
sn.add_section("settings", "Settings", "⚙", "Config")
assert_eq("item_count", sn.item_count, 4)
sn.set_active("analytics")
assert_eq("active_id", sn.active_id, "analytics")
assert_eq("item active", sn.items[1].active, true)
assert_eq("item inactive", sn.items[0].active, false)
sn.set_badge("home", 3)
assert_eq("badge set", sn.items[0].badge, 3)
sn.set_profile("Alice Smith")
assert_eq("profile_name", sn.profile_name, "Alice Smith")
assert_eq("initial", sn.profile_initial, "A")
sn.collapse()
assert_eq("collapsed", sn.collapsed, true)
assert_eq("w collapsed", sn.w, 56)
sn.expand()
assert_eq("expanded", sn.collapsed, false)
assert_eq("w expanded", sn.w, 220)
sn.toggle()
assert_eq("toggled", sn.collapsed, true)
sn.toggle()
assert_eq("re-toggled", sn.collapsed, false)
var selected_item = none
def on_sn_select(item):
    selected_item = item
sn.on_select(on_sn_select)
sn.set_pos(10, 10)
assert_eq("pos x", sn.x, 10)
sn.hide()
assert_eq("hidden", sn.visible, false)
sn.show()

# ─── OTPInput ─────────────────────────────────────────────────────────────────
section("OTPInput")
var otp = OTPInput(10, 10, 6, 48, 56)
assert_eq("digits", otp.digits, 6)
assert_eq("values len", len(otp.values), 6)
assert_eq("focused_idx init", otp.focused_idx, 0)
assert_eq("error init", otp.error, false)
assert_eq("success init", otp.success, false)
assert_eq("complete init", otp.is_complete(), false)
otp._set_digit(0, "1")
otp._set_digit(1, "2")
otp._set_digit(2, "3")
otp._set_digit(3, "4")
otp._set_digit(4, "5")
otp._set_digit(5, "6")
assert_eq("complete", otp.is_complete(), true)
assert_eq("value", otp.get_value(), "123456")
otp.set_error()
assert_eq("error", otp.error, true)
assert_eq("shake active", otp.shake_active, true)
otp.set_success()
assert_eq("success", otp.success, true)
assert_eq("error cleared", otp.error, false)
otp.clear()
assert_eq("cleared", otp.get_value(), "")
assert_eq("not complete", otp.is_complete(), false)
var complete_val = ""
def on_otp_complete(val):
    complete_val = val
otp.on_complete(on_otp_complete)
otp._set_digit(0, "9")
otp._set_digit(1, "8")
otp._set_digit(2, "7")
otp._set_digit(3, "6")
otp._set_digit(4, "5")
otp._set_digit(5, "4")
assert_eq("complete callback", complete_val, "987654")
otp.update()
otp.set_pos(50, 50)
assert_eq("pos x", otp.x, 50)
otp.hide()
assert_eq("hidden", otp.visible, false)
otp.show()
otp.disable()
assert_eq("type", type(otp), "OTPInput")
otp.enable()

# ─── CodeBlock ────────────────────────────────────────────────────────────────
section("CodeBlock")
var cb = CodeBlock(10, 10, 600, 300)
assert_eq("line_count init", cb.line_count, 0)
assert_eq("language init", cb.language, "")
cb.set_language("nython")
assert_eq("language", cb.language, "nython")
var code_str = "def greet(name):\n    var msg = \"Hello \" + name\n    return msg\n\nprint greet(\"World\")"
cb.set_code(code_str)
assert_eq("line_count", cb.line_count, 5)
assert_eq("line 0", cb.lines[0], "def greet(name):")
assert_eq("line 1", cb.lines[1], "    var msg = \"Hello \" + name")
assert_eq("line 4", cb.lines[4], "print greet(\"World\")")
var is_kw_def = cb._is_keyword("def")
assert_eq("def is keyword", is_kw_def, true)
var is_kw_var = cb._is_keyword("var")
assert_eq("var is keyword", is_kw_var, true)
var is_kw_foo = cb._is_keyword("foo")
assert_eq("foo not keyword", is_kw_foo, false)
var tc = cb._token_color("def", "def greet():")
assert_eq("keyword color r", tc.r, cb.keyword_color.r)
cb.set_pos(20, 20)
assert_eq("pos x", cb.rect.x, 20)
cb.set_size(800, 400)
assert_eq("size w", cb.rect.w, 800)
cb.hide()
assert_eq("hidden", cb.visible, false)
cb.show()

# ─── ConfettiParticle ─────────────────────────────────────────────────────────
section("ConfettiParticle")
var cp2 = ConfettiParticle(100.0, 200.0, 3.0, -5.0, Color(99, 102, 241, 255), 8, 45.0, 0.15)
assert_eq("x", cp2.x, 100.0)
assert_eq("y", cp2.y, 200.0)
assert_eq("size", cp2.size, 8)
assert_eq("alive", cp2.alive, true)
assert_eq("alpha", cp2.alpha, 255)

# ─── Confetti ─────────────────────────────────────────────────────────────────
section("Confetti")
var conf = Confetti(1280, 720)
assert_eq("active init", conf.active, false)
assert_eq("particle_count init", conf.particle_count, 0)
assert_eq("color_count", conf.color_count, 7)
conf.burst(640, 360, 30)
assert_eq("burst active", conf.active, true)
assert_eq("burst count", conf.particle_count, 30)
conf.update()
assert_true("particles moved", conf.particles[0].y != 360.0)
var conf2 = Confetti(1280, 720)
conf2.rain(20)
assert_eq("rain active", conf2.active, true)
assert_eq("rain count", conf2.particle_count, 20)
assert_eq("is done init", conf.is_done(), false)
conf.clear()
assert_eq("cleared", conf.particle_count, 0)
assert_eq("inactive", conf.active, false)
conf.show()
assert_eq("shown", conf.visible, true)
conf.hide()
assert_eq("hidden", conf.visible, false)
conf.show()

# ─── TreeMapNode ──────────────────────────────────────────────────────────────
section("TreeMapNode")
var tmn = TreeMapNode("Root", 100.0, Color(99, 102, 241, 255))
assert_eq("label", tmn.label, "Root")
assert_eq("value", tmn.value, 100.0)
assert_eq("child_count init", tmn.child_count, 0)
assert_eq("depth", tmn.depth, 0)
var child1 = TreeMapNode("A", 60.0, Color(52, 199, 89, 255))
var child2 = TreeMapNode("B", 40.0, Color(255, 149, 0, 255))
tmn.add_child(child1)
tmn.add_child(child2)
assert_eq("child_count", tmn.child_count, 2)
assert_eq("child depth", child1.depth, 1)
assert_eq("child parent not none", child1.parent != none, true)
assert_eq("total_value leaf", child1.total_value(), 60.0)
assert_eq("total_value root", tmn.total_value(), 100.0)
var grandchild = TreeMapNode("A1", 30.0, Color(220, 100, 255, 255))
child1.add_child(grandchild)
assert_eq("grandchild depth", grandchild.depth, 2)
assert_eq("child total with kids", child1.total_value(), 30.0)

# ─── TreeMap ──────────────────────────────────────────────────────────────────
section("TreeMap")
var tm = TreeMap(10, 10, 500, 400)
assert_eq("rect w", tm.rect.w, 500)
assert_eq("root init", tm.root, none)
tm.set_title("Portfolio")
assert_eq("title", tm.title, "Portfolio")
var root = TreeMapNode("Portfolio", 0.0, Color(30, 32, 48, 255))
var tech = TreeMapNode("Tech", 0.0, Color(99, 102, 241, 255))
var finance = TreeMapNode("Finance", 0.0, Color(52, 199, 89, 255))
tech.add_child(TreeMapNode("AAPL", 150.0, Color(120, 130, 255, 255)))
tech.add_child(TreeMapNode("GOOG", 120.0, Color(100, 110, 240, 255)))
tech.add_child(TreeMapNode("MSFT", 100.0, Color(80, 90, 220, 255)))
finance.add_child(TreeMapNode("JPM", 80.0, Color(80, 210, 120, 255)))
finance.add_child(TreeMapNode("BRK", 90.0, Color(60, 190, 100, 255)))
root.add_child(tech)
root.add_child(finance)
tm.set_root(root)
assert_eq("root set", tm.root != none, true)
assert_eq("tech children", tech.child_count, 3)
assert_eq("finance children", finance.child_count, 2)
tm.update()
assert_true("anim advances", tm.anim_progress > 0.0)
var tm_clicked = none
def on_tm_click(node):
    tm_clicked = node
tm.on_click(on_tm_click)
tm.set_pos(20, 20)
assert_eq("pos x", tm.rect.x, 20)
tm.set_size(600, 500)
assert_eq("size h", tm.rect.h, 500)
tm.hide()
assert_eq("hidden", tm.visible, false)
tm.show()

# ─── MarqueeItem ──────────────────────────────────────────────────────────────
section("MarqueeItem")
var mqi = MarqueeItem("BTC $65,000", "₿", Color(255, 149, 0, 255))
assert_eq("text", mqi.text, "BTC $65,000")
assert_eq("icon", mqi.icon, "₿")
assert_eq("color r", mqi.color.r, 255)

# ─── Marquee ──────────────────────────────────────────────────────────────────
section("Marquee")
var mq = Marquee(10, 10, 800, 40)
assert_eq("item_count init", mq.item_count, 0)
assert_eq("direction", mq.direction, "left")
assert_eq("offset init", mq.offset, 0.0)
assert_eq("paused init", mq.paused, false)
mq.add_item("BTC $65,000", "₿", Color(255, 149, 0, 255))
mq.add_item("ETH $3,500", "Ξ", Color(99, 102, 241, 255))
mq.add_item("SOL $180", "◎", Color(52, 199, 89, 255))
mq.add_item("DOGE $0.15", "Ð", Color(220, 180, 50, 255))
assert_eq("item_count", mq.item_count, 4)
assert_true("total_w > 0", mq.total_w > 0)
mq.set_speed(2.5)
assert_eq("speed", mq.speed, 2.5)
mq.update()
assert_true("offset advances", mq.offset > 0.0)
mq.pause()
assert_eq("paused", mq.paused, true)
var old_offset = mq.offset
mq.update()
assert_eq("no advance when paused", mq.offset, old_offset)
mq.resume()
assert_eq("resumed", mq.paused, false)
mq.update()
assert_true("advances after resume", mq.offset > old_offset)
mq.set_pos(20, 20)
assert_eq("pos x", mq.rect.x, 20)
mq.set_size(1200, 44)
assert_eq("size w", mq.rect.w, 1200)
mq.hide()
assert_eq("hidden", mq.visible, false)
mq.show()

# ─── Bubble ───────────────────────────────────────────────────────────────────
section("Bubble")
var bub = Bubble(50.0, 75.0, 20, "Google", Color(66, 133, 244, 255))
assert_eq("x_val", bub.x_val, 50.0)
assert_eq("y_val", bub.y_val, 75.0)
assert_eq("size", bub.size, 20)
assert_eq("label", bub.label, "Google")
assert_eq("anim_r init", bub.anim_r, 0.0)

# ─── BubbleChart ──────────────────────────────────────────────────────────────
section("BubbleChart")
var bch = BubbleChart(10, 10, 500, 400)
assert_eq("bubble_count init", bch.bubble_count, 0)
assert_eq("auto_range", bch.auto_range, true)
bch.set_title("Market Cap vs Revenue")
assert_eq("title", bch.title, "Market Cap vs Revenue")
bch.set_axis_labels("Revenue ($B)", "Growth (%)")
assert_eq("x_label", bch.x_label, "Revenue ($B)")
assert_eq("y_label", bch.y_label, "Growth (%)")
bch.add_bubble(80.0, 25.0, 40, "AAPL", Color(99, 102, 241, 255))
bch.add_bubble(40.0, 35.0, 25, "GOOG", Color(52, 199, 89, 255))
bch.add_bubble(65.0, 18.0, 35, "MSFT", Color(255, 149, 0, 255))
bch.add_bubble(20.0, 60.0, 18, "AMZN", Color(220, 100, 255, 255))
assert_eq("bubble_count", bch.bubble_count, 4)
assert_eq("auto x_max", bch.x_max, 100.0)
assert_eq("auto y_max", bch.y_max, 100.0)
bch.update()
assert_true("anim advances", bch.anim_progress > 0.0)
var pt = bch._to_px(80.0, 60.0)
assert_true("to_px returns list", type(pt) == "list")
var pt2 = bch._to_px(0.0, 0.0)
assert_true("to_px x in range", pt2[0] >= bch.rect.x)
bch.set_pos(20, 20)
assert_eq("pos x", bch.rect.x, 20)
bch.set_size(600, 500)
assert_eq("size w", bch.rect.w, 600)
bch.hide()
assert_eq("hidden", bch.visible, false)
bch.show()

# ─── CommandBar ───────────────────────────────────────────────────────────────
section("CommandBar")
var cmdb = CommandBar(1280, 48)
assert_eq("window_w", cmdb.window_w, 1280)
assert_eq("h", cmdb.h, 48)
assert_eq("left_count init", cmdb.left_count, 0)
assert_eq("right_count init", cmdb.right_count, 0)
assert_eq("show_search", cmdb.show_search, true)
assert_eq("search_text init", cmdb.search_text, "")
cmdb.add_left("🏠", "Home", none)
cmdb.add_left("📁", "Projects", none)
cmdb.add_left("📄", "report.pdf", none)
assert_eq("left_count", cmdb.left_count, 3)
cmdb.add_right("🔔", "Alerts", none, 3)
cmdb.add_right("👤", "Profile", none, 0)
assert_eq("right_count", cmdb.right_count, 2)
assert_eq("right badge", cmdb.right_items[0]["badge"], 3)
cmdb.set_search_placeholder("Find anything…")
assert_eq("placeholder", cmdb.search_placeholder, "Find anything…")
var search_val = ""
def on_cmdb_search(q):
    search_val = q
cmdb.on_search(on_cmdb_search)
cmdb.hide()
assert_eq("hidden", cmdb.visible, false)
cmdb.show()

# ─── Wave 5 IDE Widgets Tests ─────────────────────────────────────────────────

# ─── AutoCompleteItem ─────────────────────────────────────────────────────────
section("AutoCompleteItem")
var aci = AutoCompleteItem("print", "print(value) -> void", "function", "ƒ")
assert_eq("label", aci.label, "print")
assert_eq("kind", aci.kind, "function")
assert_eq("icon", aci.icon, "ƒ")
assert_eq("score init", aci.score, 0)

# ─── AutoComplete ─────────────────────────────────────────────────────────────
section("AutoComplete")
var ac2 = AutoComplete(280)
assert_eq("w", ac2.w, 280)
assert_eq("visible init", ac2.visible, false)
assert_eq("item_count init", ac2.item_count, 0)
ac2.register("print", "print(v)", "function", "ƒ")
ac2.register("println", "println(v)", "function", "ƒ")
ac2.register("class", "", "keyword", "K")
ac2.register("var", "", "keyword", "K")
ac2.register("def", "", "keyword", "K")
ac2.register("Panel", "class Panel", "class", "C")
assert_eq("item_count", ac2.item_count, 6)
ac2.show_at(100, 200, "pr")
assert_eq("visible", ac2.visible, true)
assert_eq("query", ac2.query, "pr")
assert_true("filtered pr", ac2.filtered_count >= 2)
ac2.update_query("print")
assert_eq("exact match", ac2.filtered_count, 2)
ac2.update_query("")
assert_eq("empty query all", ac2.filtered_count, 6)
var accepted = ""
def on_ac_accept(item):
    accepted = item.label
ac2.on_accept(on_ac_accept)
ac2.selected = 0
ac2.accept()
assert_eq("accepted", accepted, "print")
assert_eq("hidden after accept", ac2.visible, false)
ac2.show_at(100, 200, "")
ac2.update()
assert_true("anim advances", ac2.anim_y < float(ac2.item_h * 2))
var dismissed = false
def on_ac_dismiss():
    dismissed = true
ac2.on_dismiss(on_ac_dismiss)
ac2.hide()
assert_eq("dismissed", dismissed, true)
var kc = ac2._kind_color("function")
assert_eq("function color r", kc.r, 99)
var kc2 = ac2._kind_color("class")
assert_eq("class color r", kc2.r, 220)

# ─── MiniMap ──────────────────────────────────────────────────────────────────
section("MiniMap")
var mm = MiniMap(10, 10, 80, 400)
assert_eq("rect w", mm.rect.w, 80)
assert_eq("scroll_pct init", mm.scroll_pct, 0.0)
assert_eq("line_count init", mm.line_count, 0)
var code_lines = []
var mli = 0
while mli < 50:
    code_lines = code_lines + ["    var x = " + str(mli)]
    mli = mli + 1
mm.set_lines(code_lines)
assert_eq("line_count", mm.line_count, 50)
mm.set_scroll(0.5, 0.2)
assert_eq("scroll_pct", mm.scroll_pct, 0.5)
assert_eq("viewport_pct", mm.viewport_pct, 0.2)
var scroll_val = -1.0
def on_mm_scroll(pct):
    scroll_val = pct
mm.on_scroll(on_mm_scroll)
mm.set_pos(20, 20)
assert_eq("pos x", mm.rect.x, 20)
mm.set_size(100, 500)
assert_eq("size h", mm.rect.h, 500)
mm.hide()
assert_eq("hidden", mm.visible, false)
mm.show()

# ─── ChatMessage ──────────────────────────────────────────────────────────────
section("ChatMessage")
var cmsg = ChatMessage("Hello, world!", "user", "12:00")
assert_eq("text", cmsg.text, "Hello, world!")
assert_eq("sender", cmsg.sender, "user")
assert_eq("is_code init", cmsg.is_code, false)

# ─── ChatPanel ────────────────────────────────────────────────────────────────
section("ChatPanel")
var chp = ChatPanel(10, 10, 320, 500)
assert_eq("msg_count init", chp.msg_count, 0)
assert_eq("typing init", chp.typing, false)
assert_eq("bot_name", chp.bot_name, "Nython AI")
chp.add_message("Hello! How can I help?", "bot")
chp.add_message("Explain closures in Nython", "user")
chp.add_message("A closure captures variables from its enclosing scope.", "bot")
assert_eq("msg_count", chp.msg_count, 3)
assert_eq("first sender", chp.messages[0].sender, "bot")
assert_eq("second sender", chp.messages[1].sender, "user")
chp.set_typing(true)
assert_eq("typing", chp.typing, true)
chp.set_typing(false)
assert_eq("typing off", chp.typing, false)
chp.update()
var sent_msg = ""
def on_chp_send(text):
    sent_msg = text
chp.on_send(on_chp_send)
chp.input_text = "test message"
chp.clear_input()
assert_eq("input cleared", chp.input_text, "")
chp.set_pos(20, 20)
assert_eq("pos x", chp.rect.x, 20)
chp.set_size(400, 600)
assert_eq("size h", chp.rect.h, 600)
chp.hide()
assert_eq("hidden", chp.visible, false)
chp.show()

# ─── FileNode ─────────────────────────────────────────────────────────────────
section("FileNode")
var fn_dir = FileNode("src", "/project/src", true)
assert_eq("name", fn_dir.name, "src")
assert_eq("is_dir", fn_dir.is_dir, true)
assert_eq("expanded init", fn_dir.expanded, false)
assert_eq("child_count init", fn_dir.child_count, 0)
assert_eq("depth init", fn_dir.depth, 0)
var fn_file = FileNode("main.ny", "/project/src/main.ny", false)
fn_dir.add_child(fn_file)
assert_eq("child_count", fn_dir.child_count, 1)
assert_eq("child depth", fn_file.depth, 1)
fn_file.set_git_status("M")
assert_eq("git_status", fn_file.git_status, "M")
fn_file.modified = true
assert_eq("modified", fn_file.modified, true)
fn_dir.set_icon("📂")
assert_eq("icon set", fn_dir.icon, "📂")

# ─── FileTree ─────────────────────────────────────────────────────────────────
section("FileTree")
var ft = FileTree(10, 10, 200, 500)
assert_eq("root_count init", ft.root_count, 0)
assert_eq("selected_path init", ft.selected_path, "")
var proj = FileNode("project", "/project", true)
var src = FileNode("src", "/project/src", true)
var lib = FileNode("lib", "/project/lib", true)
var main_ny = FileNode("main.ny", "/project/src/main.ny", false)
var gui_ny = FileNode("gui.ny", "/project/lib/gui.ny", false)
main_ny.set_git_status("M")
src.add_child(main_ny)
lib.add_child(gui_ny)
proj.add_child(src)
proj.add_child(lib)
ft.add_root(proj)
assert_eq("root_count", ft.root_count, 1)
proj.expanded = true
src.expanded = true
var visible = ft._all_visible()
assert_eq("visible count expanded", len(visible), 4)
proj.expanded = false
var visible2 = ft._all_visible()
assert_eq("visible collapsed", len(visible2), 1)
ft.select("/project/src/main.ny")
assert_eq("selected", ft.selected_path, "/project/src/main.ny")
var sel_node = none
def on_ft_select(node):
    sel_node = node
ft.on_select(on_ft_select)
var exp_node = none
def on_ft_expand(node):
    exp_node = node
ft.on_expand(on_ft_expand)
ft.set_pos(20, 20)
assert_eq("pos x", ft.rect.x, 20)
ft.set_size(240, 600)
assert_eq("size h", ft.rect.h, 600)
ft.hide()
assert_eq("hidden", ft.visible, false)
ft.show()

# ─── EditorTab ────────────────────────────────────────────────────────────────
section("EditorTab")
var et = EditorTab("tab1", "main.ny", "/project/main.ny")
assert_eq("id", et.id, "tab1")
assert_eq("filename", et.filename, "main.ny")
assert_eq("active init", et.active, false)
assert_eq("modified init", et.modified, false)
assert_eq("ny icon", et.icon, "◈")
var et2 = EditorTab("tab2", "config.json", "/project/config.json")
assert_eq("json icon", et2.icon, "{}")
var et3 = EditorTab("tab3", "README.md", "/project/README.md")
assert_eq("md icon", et3.icon, "Md")

# ─── TabBar ───────────────────────────────────────────────────────────────────
section("TabBar")
var tb = TabBar(0, 0, 800, 36)
assert_eq("tab_count init", tb.tab_count, 0)
assert_eq("active_id init", tb.active_id, "")
tb.add_tab("t1", "main.ny", "/main.ny")
tb.add_tab("t2", "gui.ny", "/lib/gui.ny")
tb.add_tab("t3", "config.json", "/config.json")
assert_eq("tab_count", tb.tab_count, 3)
assert_eq("last active", tb.active_id, "t3")
tb.set_active("t1")
assert_eq("active set", tb.active_id, "t1")
assert_eq("t1 active", tb.tabs[0].active, true)
assert_eq("t2 inactive", tb.tabs[1].active, false)
tb.set_modified("t2", true)
assert_eq("modified", tb.tabs[1].modified, true)
var active_tab = tb.get_active()
assert_eq("get_active", active_tab.id, "t1")
var sel_tab = none
def on_tb_select(tab):
    sel_tab = tab
tb.on_select(on_tb_select)
var closed_id = ""
def on_tb_close(id):
    closed_id = id
tb.on_close(on_tb_close)
var new_called = false
def on_tb_new():
    new_called = true
tb.on_new(on_tb_new)
tb.close_tab("t2")
assert_eq("after close count", tb.tab_count, 2)
assert_eq("t2 gone", tb.tabs[0].id, "t1")
assert_eq("t3 remains", tb.tabs[1].id, "t3")
var tw = tb._tab_w()
assert_true("tab_w in range", tw >= tb.tab_min_w and tw <= tb.tab_max_w)
tb.set_pos(0, 40)
assert_eq("pos y", tb.rect.y, 40)
tb.set_size(1024, 36)
assert_eq("size w", tb.rect.w, 1024)
tb.hide()
assert_eq("hidden", tb.visible, false)
tb.show()

# ─── TerminalLine ─────────────────────────────────────────────────────────────
section("TerminalLine")
var tl2 = TerminalLine("Build succeeded", "success")
assert_eq("text", tl2.text, "Build succeeded")
assert_eq("kind", tl2.kind, "success")

# ─── TerminalPanel ────────────────────────────────────────────────────────────
section("TerminalPanel")
var tp = TerminalPanel(10, 10, 800, 250)
assert_eq("line_count init", tp.line_count, 0)
assert_eq("input_text init", tp.input_text, "")
assert_eq("prompt", tp.prompt, "nython> ")
tp.write_out("Running main.ny...")
tp.write_ok("Build successful in 0.3s")
tp.write_err("Error: undefined variable 'x' at line 5")
tp.write_warn("Deprecated: use print() instead of print")
tp.write_info("Nython v8.0 ready")
assert_eq("line_count", tp.line_count, 5)
assert_eq("first line", tp.lines[0].text, "Running main.ny...")
assert_eq("first kind", tp.lines[0].kind, "output")
assert_eq("second kind", tp.lines[1].kind, "success")
assert_eq("third kind", tp.lines[2].kind, "error")
tp.write_out("Line 1\nLine 2\nLine 3")
assert_eq("multiline count", tp.line_count, 8)
tp.clear()
assert_eq("cleared", tp.line_count, 0)
tp.write_out("Ready")
var run_cmd = ""
def on_tp_run(cmd):
    run_cmd = cmd
tp.on_run(on_tp_run)
tp.update()
assert_eq("type", type(tp), "TerminalPanel")
var lc_err = tp._line_color("error")
assert_eq("error red", lc_err.r, 255)
var lc_ok = tp._line_color("success")
assert_eq("success green", lc_ok.r, 80)
var lc_out = tp._line_color("output")
assert_eq("output color", lc_out.r, 200)
tp.set_pos(0, 450)
assert_eq("pos y", tp.rect.y, 450)
tp.set_size(1024, 220)
assert_eq("size w", tp.rect.w, 1024)
tp.hide()
assert_eq("hidden", tp.visible, false)
tp.show()


# ─── RunConfigBar ─────────────────────────────────────────────────────────────
section("RunConfigBar")
var rcb = RunConfigBar(0, 0, 900, 36)
assert_eq("mode_count", len(rcb.modes), 7)
assert_eq("active init", rcb.active_mode, 0)
assert_eq("mode 0", rcb.modes[0], "Run")
assert_eq("mode 1", rcb.modes[1], "Debug")
assert_eq("mode 2", rcb.modes[2], "Tokenize")
assert_eq("mode 3", rcb.modes[3], "AST")
assert_eq("mode 4", rcb.modes[4], "Disasm")
assert_eq("mode 5", rcb.modes[5], "REPL")
assert_eq("mode 6", rcb.modes[6], "Profile")
assert_eq("icons count", len(rcb.mode_icons), 7)
var mode_triggered = -1
var mode_name = ""
def on_rcb_mode(idx, name):
    mode_triggered = idx
    mode_name = name
rcb.on_mode(on_rcb_mode)
var run_triggered = -1
def on_rcb_run(idx, name):
    run_triggered = idx
rcb.on_run(on_rcb_run)
var mc0 = rcb._mode_color(0)
assert_eq("run color g", mc0.r, 52)
var mc1 = rcb._mode_color(1)
assert_eq("debug color r", mc1.r, 255)
var mc6 = rcb._mode_color(6)
assert_eq("profile color", mc6.r, 255)
rcb.set_pos(10, 10)
assert_eq("pos x", rcb.rect.x, 10)
rcb.set_size(1200, 40)
assert_eq("size w", rcb.rect.w, 1200)
rcb.hide()
assert_eq("hidden", rcb.visible, false)
rcb.show()
assert_eq("visible", rcb.visible, true)

# ─── TokenEntry ───────────────────────────────────────────────────────────────
section("TokenEntry")
var te = TokenEntry("def", "Def", "Name", "Keyword", 1, 4)
assert_eq("value", te.value, "def")
assert_eq("tok_type", te.tok_type, "Def")
assert_eq("tok_kind", te.tok_kind, "Name")
assert_eq("tok_class", te.tok_class, "Keyword")
assert_eq("line", te.line, 1)
assert_eq("col", te.col, 4)

# ─── TokenViewer ──────────────────────────────────────────────────────────────
section("TokenViewer")
var tv = TokenViewer(0, 0, 900, 500)
assert_eq("token_count init", tv.token_count, 0)
assert_eq("visible init", tv.visible, false)
assert_eq("item_h", tv.item_h, 28)
var kw_c = tv._class_color("Keyword")
assert_eq("keyword purple r", kw_c.r, 196)
var id_c = tv._class_color("Identifier")
assert_eq("identifier blue b", id_c.b, 255)
var lit_c = tv._class_color("Literal")
assert_eq("literal green g", lit_c.g, 215)
var del_c = tv._class_color("Delimiter")
assert_eq("delimiter muted", del_c.r, 120)
var op_c = tv._class_color("Operator")
assert_eq("operator orange", op_c.r, 248)
var raw_tokens = [
    {"v": "def",       "t": "Def",        "k": "Name",       "c": "Keyword",    "ln": 1, "col": 4},
    {"v": "factorial", "t": "Identifier", "k": "Identifier", "c": "Identifier", "ln": 1, "col": 4},
    {"v": "(",         "t": "ParenOpen",  "k": "LeftParen",  "c": "Default",    "ln": 1, "col": 1},
    {"v": "n",         "t": "Identifier", "k": "Identifier", "c": "Identifier", "ln": 1, "col": 1},
    {"v": ")",         "t": "ParenClose", "k": "RightParen", "c": "Default",    "ln": 1, "col": 1},
    {"v": "42",        "t": "Integer",    "k": "Number",     "c": "Literal",    "ln": 3, "col": 4},
    {"v": "x",         "t": "Identifier", "k": "Identifier", "c": "Identifier", "ln": 3, "col": 4},
    {"v": "=",         "t": "Assign",     "k": "Assign",     "c": "Assignment", "ln": 3, "col": 2}
]
tv.set_raw(raw_tokens)
assert_eq("token_count", tv.token_count, 8)
assert_eq("first token val", tv.tokens[0].value, "def")
assert_eq("first token class", tv.tokens[0].tok_class, "Keyword")
assert_eq("number token", tv.tokens[5].value, "42")
assert_eq("assign class", tv.tokens[7].tok_class, "Assignment")
var clicked_tok = none
def on_tv_click(tok):
    clicked_tok = tok
tv.on_click(on_tv_click)
tv.set_pos(10, 10)
assert_eq("pos x", tv.rect.x, 10)
tv.set_size(1100, 600)
assert_eq("size h", tv.rect.h, 600)
tv.show()
assert_eq("visible", tv.visible, true)
tv.hide()

# ─── ASTNode2 ─────────────────────────────────────────────────────────────────
section("ASTNode2")
var an = ASTNode2("Function", '<Function name="foo" params="2">', 1)
assert_eq("tag", an.tag, "Function")
assert_eq("depth", an.depth, 1)
assert_eq("expanded", an.expanded, true)
assert_eq("has_children", an.has_children, false)

# ─── ASTViewer ────────────────────────────────────────────────────────────────
section("ASTViewer")
var av = ASTViewer(0, 0, 700, 500)
assert_eq("node_count init", av.node_count, 0)
assert_eq("visible init", av.visible, false)
var script_c = av._tag_color("Script")
assert_eq("Script color r", script_c.r, 99)
var func_c = av._tag_color("Function")
assert_eq("Function color b", func_c.b, 255)
var class_c = av._tag_color("Class")
assert_eq("Class color r", class_c.r, 252)
var var_c = av._tag_color("VarDecl")
assert_eq("VarDecl green g", var_c.g, 215)
var if_c = av._tag_color("If")
assert_eq("If orange r", if_c.r, 255)
var ast_xml = "<Script>" + "\n   <Source/>" + "\n   <Statements>" + "\n      <Function name=\"foo\">" + "\n      </Function>" + "\n      <VarDecl name=\"x\"/>" + "\n   </Statements>" + "\n</Script>"
av.parse_xml(ast_xml)
assert_true("nodes parsed", av.node_count > 0)
assert_eq("first tag", av.nodes[0].tag, "Script")
assert_true("Script has children", av.nodes[0].has_children)
av.set_pos(5, 5)
assert_eq("pos y", av.rect.y, 5)
av.set_size(800, 600)
assert_eq("size w", av.rect.w, 800)
av.show()
assert_eq("visible", av.visible, true)
av.hide()

# ─── BreakpointEntry ──────────────────────────────────────────────────────────
section("BreakpointEntry")
var bp = BreakpointEntry("main.ny", 42, true)
assert_eq("file", bp.file, "main.ny")
assert_eq("line", bp.line, 42)
assert_eq("enabled", bp.enabled, true)
assert_eq("hit_count init", bp.hit_count, 0)
assert_eq("condition init", bp.condition, "")

# ─── WatchEntry ───────────────────────────────────────────────────────────────
section("WatchEntry")
var we = WatchEntry("self.count", "42")
assert_eq("expr", we.expr, "self.count")
assert_eq("value", we.value, "42")
assert_eq("changed init", we.changed, false)

# ─── DebugPanel ───────────────────────────────────────────────────────────────
section("DebugPanel")
var dp = DebugPanel(0, 0, 600, 400)
assert_eq("visible init", dp.visible, false)
assert_eq("bp_count init", dp.bp_count, 0)
assert_eq("watch_count init", dp.watch_count, 0)
assert_eq("stack_depth init", dp.stack_depth, 0)
assert_eq("active_tab init", dp.active_tab, 0)
assert_eq("tabs count", len(dp.tabs), 3)
assert_eq("tab 0", dp.tabs[0], "Breakpoints")
assert_eq("tab 1", dp.tabs[1], "Watch")
assert_eq("tab 2", dp.tabs[2], "Call Stack")
dp.add_breakpoint("main.ny", 12)
dp.add_breakpoint("app.ny", 34)
assert_eq("bp_count", dp.bp_count, 2)
assert_eq("bp file", dp.breakpoints[0].file, "main.ny")
assert_eq("bp line", dp.breakpoints[0].line, 12)
assert_eq("bp enabled", dp.breakpoints[0].enabled, true)
dp.add_watch("self.counter", "0")
dp.add_watch("result", "none")
assert_eq("watch_count", dp.watch_count, 2)
assert_eq("watch expr", dp.watches[0].expr, "self.counter")
dp.update_watch("self.counter", "7")
assert_eq("watch updated", dp.watches[0].value, "7")
assert_eq("watch changed", dp.watches[0].changed, true)
dp.update_watch("self.counter", "7")
assert_eq("watch unchanged same", dp.watches[0].changed, false)
dp.push_frame("<module>", "main.ny", 1)
dp.push_frame("factorial", "main.ny", 5)
dp.push_frame("factorial", "main.ny", 5)
assert_eq("stack depth", dp.stack_depth, 3)
assert_eq("frame 0 name", dp.call_stack[0]["name"], "<module>")
assert_eq("frame 1 name", dp.call_stack[1]["name"], "factorial")
dp.remove_breakpoint("app.ny", 34)
assert_eq("bp after remove", dp.bp_count, 1)
assert_eq("remaining bp", dp.breakpoints[0].file, "main.ny")
dp.clear_stack()
assert_eq("stack cleared", dp.stack_depth, 0)
var step_kind = ""
def on_dp_step(kind):
    step_kind = kind
dp.on_step(on_dp_step)
var cont_called = false
def on_dp_cont():
    cont_called = true
dp.on_continue(on_dp_cont)
var stop_called = false
def on_dp_stop():
    stop_called = true
dp.on_stop(on_dp_stop)
dp.set_pos(10, 10)
assert_eq("pos x", dp.rect.x, 10)
dp.set_size(800, 500)
assert_eq("size h", dp.rect.h, 500)
dp.show()
assert_eq("visible", dp.visible, true)
dp.hide()

# ─── ProfileEntry ─────────────────────────────────────────────────────────────
section("ProfileEntry")
var pe = ProfileEntry("factorial", "function", 120, 45.2, 38.7)
assert_eq("name", pe.name, "factorial")
assert_eq("kind", pe.kind, "function")
assert_eq("calls", pe.calls, 120)
assert_eq("pct init", pe.pct, 0.0)

# ─── ProfilerPanel ────────────────────────────────────────────────────────────
section("ProfilerPanel")
var pp = ProfilerPanel(0, 0, 900, 400)
assert_eq("entry_count init", pp.entry_count, 0)
assert_eq("total_ms init", pp.total_ms, 0.0)
assert_eq("visible init", pp.visible, false)
pp.set_total(200.0)
pp.add_entry("factorial", "function", 120, 80.0, 60.0)
pp.add_entry("Counter.__init__", "method", 5, 10.0, 10.0)
pp.add_entry("Counter.inc", "method", 50, 30.0, 25.0)
pp.add_entry("<module>", "module", 1, 200.0, 80.0)
assert_eq("entry_count", pp.entry_count, 4)
assert_eq("first name", pp.entries[0].name, "factorial")
assert_eq("first calls", pp.entries[0].calls, 120)
assert_eq("pct set", pp.entries[0].pct, 0.4)
assert_eq("module pct", pp.entries[3].pct, 1.0)
pp.set_pos(5, 5)
assert_eq("pos x", pp.rect.x, 5)
pp.set_size(1100, 500)
assert_eq("size w", pp.rect.w, 1100)
pp.show()
assert_eq("visible", pp.visible, true)
pp.hide()
pp.clear()
assert_eq("cleared", pp.entry_count, 0)

# ─── REPLPanel ────────────────────────────────────────────────────────────────
section("REPLPanel")
var rp = REPLPanel(0, 0, 900, 400)
assert_eq("hist_count init", rp.hist_count, 0)
assert_eq("input init", rp.input_text, "")
assert_eq("visible init", rp.visible, false)
rp.write(">>> var x = 42", "prompt")
rp.write("42", "result")
rp.write(">>> print x", "prompt")
rp.write("42", "ok")
rp.write(">>> 1/0", "prompt")
rp.write("Error: division by zero", "error")
assert_eq("hist_count", rp.hist_count, 6)
assert_eq("first kind", rp.history[0]["kind"], "prompt")
assert_eq("result kind", rp.history[1]["kind"], "result")
assert_eq("error kind", rp.history[5]["kind"], "error")
var prompt_c = rp._line_color("prompt")
assert_eq("prompt color r", prompt_c.r, 99)
var err_c = rp._line_color("error")
assert_eq("error color r", err_c.r, 255)
var ok_c = rp._line_color("ok")
assert_eq("ok color g", ok_c.g, 220)
var info_c = rp._line_color("info")
assert_eq("info color b", info_c.b, 255)
var result_c = rp._line_color("result")
assert_eq("result color r", result_c.r, 248)
var exec_expr = ""
def on_rp_exec(e):
    exec_expr = e
rp.on_execute(on_rp_exec)
rp.clear()
assert_eq("cleared", rp.hist_count, 0)
rp.write(">>> ready", "prompt")
rp.set_pos(10, 10)
assert_eq("pos x", rp.rect.x, 10)
rp.set_size(1100, 500)
assert_eq("size h", rp.rect.h, 500)
rp.show()
assert_eq("visible", rp.visible, true)
rp.hide()

print ""
print "Results: " + str(passed) + " passed, " + str(failed) + " failed"
if failed == 0:
    print "=== ALL GUI TESTS PASSED ==="
else:
    print "=== SOME GUI TESTS FAILED ==="
