# nython: module    (import it by name: it runs in a module scope of its own)
# lib/unicodedata.ny - Python's unicodedata, the character names (round 77).
#
#     import unicodedata
#     unicodedata.name("—")            # 'EM DASH'
#     unicodedata.lookup("snowman")         # '☃'
#
# lookup(name)          the character called `name`, without regard to case;
#                       KeyError "undefined character name 'x'" otherwise
# name(chr[, default])  its name; ValueError "no such name" (or default)
#                       when it has none
# unidata_version       "14.0.0", the database the names come from
#
# The names are CPython 3.11's own, every one of them (138,552: the 32,647
# stored ones, CJK/Tangut-style names made from the code point, Hangul
# syllables composed from their jamo) - the table string literals' \N{...}
# escapes use (include/NyUniNamesData.hpp, generated by
# tools/gen_unicode_names.py; src/NyUniNames.cpp), reached through the
# _ny_unicode_lookup / _ny_unicode_name builtins on both engines.
#
# Not here: name aliases and named sequences (lookup("LATIN SMALL LETTER
# R WITH TILDE") is a KeyError), and the rest of the module - category,
# bidirectional, combining, east_asian_width, mirrored, decomposition,
# decimal/digit/numeric, normalize/is_normalized, ucd_3_2_0.

__all__ = ["lookup", "name", "unidata_version"]

unidata_version = "14.0.0"


def lookup(name):
    if not isinstance(name, str):
        raise TypeError("lookup() argument must be str, not " + type(name).__name__)
    c = _ny_unicode_lookup(name)
    if c is None:
        raise KeyError("undefined character name '" + name + "'")
    return c


_no_default = object()


def name(chr, default=_no_default):
    if not isinstance(chr, str):
        raise TypeError("name() argument 1 must be a unicode character, not " + type(chr).__name__)
    if len(chr) != 1:
        raise TypeError("name() argument 1 must be a unicode character, not str")
    n = _ny_unicode_name(chr)
    if n == "":
        if default is _no_default:
            raise ValueError("no such name")
        return default
    return n
