print "========================================="
print "  Nython v0.3.0 Real-World Demo          "
print "========================================="
import math

print ""
print "--- Student Grade Calculator ---"
class Student:
    def init(self, name, grades):
        self.name = name
        self.grades = grades
    def average(self):
        return self.grades.reduce(lambda a, b: a + b, 0) / len(self.grades)
    def letter_grade(self):
        var avg = self.average()
        if avg >= 90:
            return "A"
        elif avg >= 80:
            return "B"
        elif avg >= 70:
            return "C"
        else:
            return "F"

var alice = Student("Alice", [95, 87, 92, 88])
var bob = Student("Bob", [72, 68, 75, 80])
print "{}: avg={}, grade={}".format(alice.name, str(alice.average()), alice.letter_grade())
print "{}: avg={}, grade={}".format(bob.name, str(bob.average()), bob.letter_grade())

print ""
print "--- Shape Hierarchy ---"
class Shape:
    def describe(self):
        return "{}: area={}".format(self.name, str(self.area()))

class Circle(Shape):
    def init(self, r):
        self.name = "Circle"
        self.radius = r
    def area(self):
        return PI * self.radius * self.radius

class Rectangle(Shape):
    def init(self, w, h):
        self.name = "Rect"
        self.width = w
        self.height = h
    def area(self):
        return self.width * self.height

print Circle(5).describe()
print Rectangle(4, 6).describe()

print ""
print "--- Functional Pipeline ---"
var data = [12, 5, 8, 3, 19, 7, 15, 2, 11, 6]
print data.filter(lambda x: x > 5).map(lambda x: x * 2).sort()
print "Sum: " + str(data.reduce(lambda a, b: a + b, 0))

print ""
print "--- Fibonacci ---"
def fib_list(n):
    var result = []
    var a = 0
    var b = 1
    for i in range(n):
        result.append(a)
        var temp = a + b
        a = b
        b = temp
    return result
print fib_list(15)

print ""
print "--- Prime Sieve ---"
def sieve(n):
    var primes = []
    for i in range(2, n):
        var is_prime = true
        for p in primes:
            if p * p > i:
                break
            if i % p == 0:
                is_prime = false
                break
        if is_prime:
            primes.append(i)
    return primes
print sieve(50)

print ""
print "--- Matrix ---"
var grid = [[1,0,0],[0,5,0],[0,0,9]]
for row in grid:
    print row

print ""
print "--- Closure Counter ---"
def make_counter(name, start):
    var n = start
    def inc():
        n = n + 1
        return name + ": " + str(n)
    return inc

var hits = make_counter("hits", 0)
print hits()
print hits()
print hits()

print ""
print "--- File IO ---"
import io
write_file("demo_output.txt", "Generated by Nython v0.3.0")
print "File written: " + str(file_exists("demo_output.txt"))
print "Content: " + read_file("demo_output.txt")

print ""
print "========================================="
print "  All features working!                  "
print "========================================="
