var s = "Hello World"
print s.upper()
print s.lower()
print s.split(" ")
print s.replace("World", "Nython")
print s.find("World")
print s.startswith("Hello")
print s.endswith("World")
print s.contains("llo")
print s.length()
print s.reverse()
print s.charAt(0)
print s.substring(0, 5)
print "  spaces  ".strip()
print ", ".join(["a", "b", "c"])
