#ifndef __INTERPRETER__HPP
#define __INTERPRETER__HPP

#ifdef _WIN32
#include <io.h>
#endif
#include <mutex>
#include <regex>
#include <thread>
#include <atomic>
#include <locale>
#include <chrono>
#ifndef _WIN32
#include <fcntl.h>
#endif
#include <clocale>
#include <cassert>
#include "Thread.hpp"
#include <sys/stat.h>
#include <Runflags.hpp>
#include "Runnable.hpp"
#include "GarbageCollector.hpp"

#include <cstdio>
#ifdef _WIN32
#include <io.h>
#endif
#ifndef _WIN32
#include <fcntl.h>
#endif
#include <fstream>
#include <iostream>

using nython::interpreter::RunFlags;

namespace nython {
namespace interpreter {

using kernel::Value;

static const std::string kHelpMessage =
    "Welcome to Nython 1.0.0! \n\n"
    "To use this interactive REPL, just type in regular Nython commands and hit\n"
    "enter. You can also make use of the following commands: \n\n"
    "Usage: nython [filename] [flags] [--] [arguments]\n"
    "    -f FLAG, --flag FLAG             Set a flag\n"
    "    -h, --help                       Print this help message\n"
    "    -v, --version                    Prints the version number\n"
    "    -l, --license                    Prints the license\n"
    "    --vmdir                          Prints the VMDIR environment variable\n"
    "\n"
    "Flags:\n"
    "    dump_ast                         Display the AST of the input file\n"
    "    dump_tokens                      Display tokens of the input file\n"
    "    dump_asm                         Display a disassembly of the input file\n"
    "    dump_file_include filename       Add a file to the list of files to be dumped\n"
    "    skipexec                         Don't execute after parsing\n"
    "    instruction_profile              Display a profile of all executed instructions\n"
    "    trace_gc                         Display statistics about the gc at runtime\n"
    "\n"
    "Examples:\n"
    "\n"
    "    Executing a file:\n"
    "    $ nython file.ny\n"
    "\n"
    "    Dumping generated bytecodes for a file:\n"
    "    $ nython file.ny -fskipexec -fdump_asm\n"
    "\n"
    "    Dumping generated AST for a file:\n"
    "    $ nython file.ny -fskipexec -fdump_ast\n"
    "\n"
    "    Disabling the cli-parser using '--'\n"
    "    $ nython file.ny -- -fdump_asm -fskipexec";

static const std::string kLicense =
    "MIT License \n"
    "\n"
    "Copyright (c) 2017 - 2020 Litet Li Mbeleg Perrin \n"
    "\n"
    "Permission is hereby granted, free of charge, to any person obtaining a copy \n"
    "of this software and associated documentation files (the \"Software\"), to deal \n"
    "in the Software without restriction, including without limitation the rights \n"
    "to use, copy, modify, merge, publish, distribute, sub license, and/or sell \n"
    "copies of the Software, and to permit persons to whom the Software is \n"
    "furnished to do so, subject to the following conditions: \n"
    "The above copyright notice and this permission notice shall be included in all \n"
    "copies or substantial portions of the Software. \n"
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR \n"
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, \n"
    "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE \n"
    "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER \n"
    "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, \n"
    "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE \n"
    "SOFTWARE.";

using gc::MemoryCell;
using gc::GarbageCollector;

struct Interpreter extends Runnable {

    friend class GarbageCollector;
    std::string input;
    std::string program;
	std::string historyPath;
    RunFlags flags;
    GarbageCollector gc;
    std::atomic<bool> running;

	Interpreter(Reporter* reporter, int argc, char** argv, char** environment);
	~Interpreter();

	int run();
    void usage();/// displays interpreter usage
    Value eval(const std::string& code);/// evaluate a corresponding code

    /*
      You can pass _O_U16TEXT, _O_U8TEXT, or _O_WTEXT
      to enable Unicode mode
      _O_TEXT to "translated mode" aka ANSI
      _O_BINARY sets binary (untranslated) mode,
      SetConsoleOutputCP(CP_UTF8);
      SetConsoleCP(CP_UTF8);
     */

    inline static void changeConsoleCharacterMode(){
    }

    template<typename T>
    T* create() {
        MemoryCell* cell = this->gc.allocate();
        T* object = nullptr;
        try{
            object = new T();
        }catch(...){
            this->gc.do_collect();
            try{
                object = new T();
            }catch(std::bad_alloc& e){
                throw e;
            }
        }
        cell->value = object;
        return cell->as<T>();
    }

    template<class T,class First,class...Rest>
    T* create(First&& first, Rest&&... rest) {
        MemoryCell* cell = this->gc.allocate();
        T* object = nullptr;
        try{
            object = new T(std::forward<First&&>(first),std::forward<Rest&&>(rest)...);
        }catch(...){
            this->gc.do_collect();
            try{
                object = new T(std::forward<First&&>(first),std::forward<Rest&&>(rest)...);
            }catch(std::bad_alloc& e){
                throw e;
            }
        }
        cell->value = object;
        return cell->as<T>();
    }

    inline static bool FileExists(const std::string& name) {
        struct stat buffer;
        return !name.empty() && (stat (name.c_str(), &buffer) == 0);
    }

    inline static void trim(std::string* input) {
        *input = std::regex_replace(*input, std::regex("^ +| +$"), "$1");
    }

	DISALLOW_COPY_AND_ASSIGN(Interpreter)
};

}
}

#endif // __INTERPRETER__HPP

