#pragma once
// Unicode character names (round 77): what a string literal's \N{...}
// escape names, as in CPython - include/NyUniNamesData.hpp (generated by
// tools/gen_unicode_names.py from Python's own unicodedata) plus the names
// Unicode derives from the code point (CJK UNIFIED IDEOGRAPH-4E00, HANGUL
// SYLLABLE GA, ...). Names match without regard to case, as
// unicodedata.lookup's do. Name aliases and named sequences are not here.
#include <cstdint>
#include <string>

namespace nyuni {

// The code point called `name`; false when no character has that name.
bool lookup(const std::string& name, uint32_t& cp);

// The name of code point cp, "" when it has none (unicodedata.name).
std::string name(uint32_t cp);

}  // namespace nyuni
