#!/usr/bin/env python3
"""Generates include/NyUniNamesData.hpp - the Unicode character names behind
string literals' \\N{...} escapes (src/Lexer.cpp, through src/NyUniNames.cpp)
- from the running Python's own database (round 77), so that \\N{EM DASH},
\\N{snowman} and \\N{CJK UNIFIED IDEOGRAPH-4E00} name what they name in
CPython:

  kWords    every word of every name, the most frequent first, one per line
  kNames    per named code point, in order: the distance from the previous
            one (a varint), its word count, its words' indices (one byte
            below 128, else two) - base64 in the source
  kDerived  the names made from the code point itself (CJK UNIFIED
            IDEOGRAPH-4E00, TANGUT IDEOGRAPH-17000, ...): a prefix and the
            range it covers. Hangul syllables are composed from their jamo
            in src/NyUniNames.cpp, as the Unicode standard defines them.

    python3 tools/gen_unicode_names.py > include/NyUniNamesData.hpp
"""
import base64
import sys
import unicodedata

MAX = sys.maxunicode + 1
HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3

named = []           # (code point, name) of the names stored word by word
derived = {}         # prefix -> [code points] for PREFIX + "%04X"
for cp in range(MAX):
    try:
        n = unicodedata.name(chr(cp))
    except ValueError:
        continue
    if HANGUL_FIRST <= cp <= HANGUL_LAST:
        continue
    h = "%04X" % cp
    if n.endswith("-" + h):
        derived.setdefault(n[: -len(h)], []).append(cp)
        continue
    named.append((cp, n))

freq = {}
for cp, n in named:
    for w in n.split(" "):
        freq[w] = freq.get(w, 0) + 1
words = sorted(freq, key=lambda w: (-freq[w], w))
index = {w: i for i, w in enumerate(words)}
assert len(words) < 0x8000

out = bytearray()
prev = -1
for cp, n in named:
    d = cp - prev
    prev = cp
    while True:
        b = d & 0x7F
        d >>= 7
        if d:
            out.append(b | 0x80)
        else:
            out.append(b)
            break
    ws = n.split(" ")
    assert len(ws) < 256
    out.append(len(ws))
    for w in ws:
        i = index[w]
        if i < 0x80:
            out.append(i)
        else:
            out.append(0x80 | (i >> 8))
            out.append(i & 0xFF)

ranges = []
for prefix, cps in derived.items():
    start = last = cps[0]
    for c in cps[1:]:
        if c != last + 1:
            ranges.append((prefix, start, last))
            start = c
        last = c
    ranges.append((prefix, start, last))
ranges.sort(key=lambda r: r[1])

p = print
p("// include/NyUniNamesData.hpp - GENERATED by tools/gen_unicode_names.py from Python %s"
  % sys.version.split()[0])
p("// (Unicode %s): %d names stored word by word, %d ranges of derived names."
  % (unicodedata.unidata_version, len(named), len(ranges)))
p("// Do not edit by hand; used by src/NyUniNames.cpp only.")
p("#pragma once")
p("#include <cstdint>")
p("namespace nyuni_data {")
p("")
p("static const int kNamed = %d;" % len(named))
p("")
p("static const char* const kWords =")
line = ""
for w in words:
    piece = w + "\\n"
    if len(line) + len(piece) > 96:
        p('    "' + line + '"')
        line = ""
    line += piece
if line:
    p('    "' + line + '"')
p("    ;")
p("")
p("// %d bytes, base64" % len(out))
p("static const char* const kNames =")
b64 = base64.b64encode(bytes(out)).decode("ascii")
for i in range(0, len(b64), 100):
    p('    "' + b64[i:i + 100] + '"')
p("    ;")
p("")
p("struct Derived { const char* prefix; uint32_t first, last; };")
p("static const Derived kDerived[] = {")
for prefix, a, b in ranges:
    p('    {"%s", 0x%X, 0x%X},' % (prefix, a, b))
p("};")
p("")
p("}  // namespace nyuni_data")
