#!/usr/bin/env python3
"""Generates include/NyReTables.hpp - the Unicode tables of the regular
expression engine (src/builtins/nyre.cpp) - from the running Python's own
database, so that \\w \\d \\s, group-name identifiers and case-insensitive
matching agree with CPython's sre:

  word      str.isalnum() or "_"                  (sre: Py_UNICODE_ISALNUM)
  digit     str.isdecimal()                       (Py_UNICODE_ISDECIMAL)
  space     str.isspace()                         (Py_UNICODE_ISSPACE)
  cased     _sre.unicode_iscased
  lower     _sre.unicode_tolower                  (backreferences compare it)
  canon     one representative per case-insensitive class: the smallest of
            lower(c) and re._casefix's extra cases of lower(c) - two
            characters match under IGNORECASE exactly when their canons
            are equal (sre: lower(a) == lower(b) or a fix links them)
  idstart / idcont    str.isidentifier() for (?P<name>...)

    python3 tools/gen_re_tables.py > include/NyReTables.hpp
"""
import sys
import unicodedata
import _sre
from re import _casefix

MAX = sys.maxunicode + 1


def ranges(pred):
    out, start = [], None
    for c in range(MAX):
        if pred(c):
            if start is None:
                start = c
        elif start is not None:
            out.append((start, c - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def emit(name, rows):
    print("static const uint32_t %s[][2] = {" % name)
    for i in range(0, len(rows), 6):
        print("    " + " ".join("{0x%X,0x%X}," % r for r in rows[i:i + 6]))
    print("};")


def canon(c):
    lo = _sre.unicode_tolower(c)
    return min((lo,) + tuple(_casefix._EXTRA_CASES.get(lo, ())))


lower = [(c, _sre.unicode_tolower(c)) for c in range(MAX) if _sre.unicode_tolower(c) != c]
canons = [(c, canon(c)) for c in range(MAX) if canon(c) != c]
classes = {}
for c, k in canons:
    classes.setdefault(k, {k}).add(c)
members = sorted((k, m) for k, ms in classes.items() for m in ms)

print("// include/NyReTables.hpp - GENERATED by tools/gen_re_tables.py from Python %s"
      % sys.version.split()[0])
print("// (Unicode %s). Do not edit by hand; used by src/builtins/nyre.cpp only."
      % unicodedata.unidata_version)
print("#pragma once")
print("#include <cstdint>")
print("namespace nyre_tables {")
emit("kWord", ranges(lambda c: c == 95 or chr(c).isalnum()))
emit("kDigit", ranges(lambda c: chr(c).isdecimal()))
emit("kSpace", ranges(lambda c: chr(c).isspace()))
emit("kCased", ranges(lambda c: _sre.unicode_iscased(c)))
emit("kIdStart", ranges(lambda c: chr(c).isidentifier()))
emit("kIdCont", ranges(lambda c: ("a" + chr(c)).isidentifier()))
emit("kLower", lower)
emit("kCanon", canons)
emit("kClass", members)
print("} // namespace nyre_tables")
